### ISSUE TITLE
Xid (PCI:0000:2b:00): 31 MMU Fault: ENGINE GRAPHICS GPC6 GPCCLIENT_T1_13 faulted @ 0x6f17_04027000. Fault is of type FAULT_PDE ACCESS_TYPE_VIRT_WRITE

### ISSUE THREAD

**Issue by aginies** [NVIDIA/open-gpu-kernel-modules#1030]
### NVIDIA Open GPU Kernel Modules Version

590.48.01

### Please confirm this issue does not happen with the proprietary driver (of the same version). This issue tracker is only for bugs specific to the open kernel driver.

- [ ] I confirm that this does not happen with the proprietary driver package.

### Operating System and Version

openSUSE Tumbleweed

### Kernel Release

6.18.9-1-default

### Please confirm you are running a stable release kernel (e.g. not a -rc). We do not accept bug reports for unreleased kernels.

- [ ] I am running on a stable kernel release.

### Hardware: GPU

GPU 0: NVIDIA GeForce RTX 5090

### Describe the bug

There is an issue with the linux kernel driver. Can't run ollama or llama.ccp without getting an error, and this is working fine under windows, so seems this is not an Hardware or a firmware issue.

## llama.ccp
./llama-bench -m ~/testcuda/qwen2.5-coder-3b-instruct-q4_0.gguf 
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 5090, compute capability 12.0, VMM: yes
| model                          |       size |     params | backend    | ngl |          test |                  t/s |
| ------------------------------ | ---------: | ---------: | ---------- | --: | ------------: | -------------------: |
RMS_NORM: src0_d=0x7f6f32000000 (attr_err=0, type=2), dst_d=0x7f6f32501000 (attr_err=0, type=2)
  ne00=2048, ne01=512, ne02=1, ne03=1, s01=2048, s02=1048576, s03=1048576
MUL_OP: src0=0x7f6f32501000 (err=0, type=2), src1=0x7f6e7136f800 (err=0, type=2), dst=0x7f6f32501000 (err=0, type=2)
  src0: type=f32, shape=[2048,512,1,1]
  src1: type=f32, shape=[2048,1,1,1]
  dst: type=f32, shape=[2048,512,1,1]

!!! CUDA KERNEL FAILED: op=MUL (6)
    src0: f32, shape=[2048,512,1,1]
    dst: f32, shape=[2048,512,1,1]

=== CUDA ERROR DETAILS ===
CUDA error: an illegal memory access was encountered
  current device: 0
  function: ggml_cuda_compute_forward
  location: /home/aginies/open-gpu-kernel-modules/llama.cpp/ggml/src/ggml-cuda/ggml-cuda.cu:2332
  statement: err

## With ollama
ollama serve
level=INFO source=types.go:42 msg="inference compute" id=GPU-446f513c-0699-5337-2cd0-9fa3d507cc94 filter_id="" library=CUDA compute=12.0 name=CUDA0 description="NVIDIA GeForce RTX 5090" libdirs=ollama,cuda_v13 driver=13.1 pci_id=0000:2b:00.0 type=discrete total="31.8 GiB" available="31.3 GiB"

ollama run llama3.2
 time=2026-02-18T18:39:02.879+01:00 level=ERROR source=server.go:304 msg="llama runner terminated" error="exit status 2"
⠦ time=2026-02-18T18:39:03.117+01:00 level=INFO source=sched.go:493 msg="Load failed" model=/home/aginies/.ollama/models/blobs/sha256-dde5aa3fc5ffc17176b5e8bdc82f587b24b2678c6c66101bf7da77af9f7ccdff error="llama runner process has terminated: CUDA error: an illegal memory access was encountered\n  current device: 0, in function ggml_backend_cuda_buffer_clear at //ml/backend/ggml/ggml/src/ggml-cuda/ggml-cuda.cu:790\n  cudaStreamSynchronize(((cudaStream_t)0x2))\n//ml/backend/ggml/ggml/src/ggml-cuda/ggml-cuda.cu:94: CUDA error"
[GIN] 2026/02/18 - 18:39:03 | 500 |  4.656141722s |       127.0.0.1 | POST     "/api/generate"
Error: 500 Internal Server Error: llama runner process has terminated: CUDA error: an illegal memory access was encountered
  current device: 0, in function ggml_backend_cuda_buffer_clear at //ml/backend/ggml/ggml/src/ggml-cuda/ggml-cuda.cu:790
  cudaStreamSynchronize(((cudaStream_t)0x2))
//ml/backend/ggml/ggml/src/ggml-cuda/ggml-cuda.cu:94: CUDA error

### dmesg
[  130.456250] [   T1946] NVRM: Xid (PCI:0000:2b:00): 31, pid=1942, name=llama-bench, channel 0x00000002, intr 00000000. MMU Fault: ENGINE GRAPHICS GPC6 GPCCLIENT_T1_13 faulted @ 0x6f6f_320c2000. Fault is of type FAULT_PDE ACCESS_TYPE_VIRT_READ
[  130.467839] [   T1964] llama-bench[1964]: segfault at 206e03fe0 ip 00007f71b508324c sp 00007ffe8b911a10 error 4 in libcuda.so.590.48.01[48324c,7f71b4d67000+108c000] likely on CPU 11 (core 11, socket 0)
[  130.467844] [   T1964] Code: ce ff 83 3d 81 03 9b 05 01 49 8b 1c 24 76 0e 8b 05 89 03 9b 05 85 c0 0f 84 91 00 00 00 49 8b 44 24 10 41 8b 4c 24 24 48 8b 13 <8b> 00 41 39 c5 0f 84 89 00 00 00 8b b3 40 40 00 00 48 89 f0 89 8c

## some testing
Sounds like there is an issue with chunk size on my card:
test_chunk_sizes.cu: https://paste.opensuse.org/pastes/5d419b50384b
I build it with nvcc, and test it:

./test_chunk_sizes 
Testing chunk sizes to find failure boundary...
Testing chunk size 512KB (524288 bytes)... PASS
Testing chunk size 576KB (589824 bytes)... PASS
Testing chunk size 600KB (614400 bytes)... PASS
Testing chunk size 620KB (634880 bytes)... PASS
Testing chunk size 630KB (645120 bytes)... PASS
Testing chunk size 635KB (650240 bytes)... PASS
Testing chunk size 639KB (654336 bytes)... PASS
Testing chunk size 640KB (655360 bytes)... cudaDeviceSynchronize failed at offset 0: an illegal memory access was encountered
FAIL
Testing chunk size 641KB (656384 bytes)... cudaMalloc failed: CUDA-capable device(s) is/are busy or unavailable

### dmesg
NVRM: Xid (PCI:0000:2b:00): 31, pid=2250, name=test_chunk_size, channel 0x00000002, intr 00000000. MMU Fault: ENGINE GRAPHICS GPC6 GPCCLIENT_T1_13 faulted @ 0x6fb6_c401b000. Fault is of type FAULT_PDE ACCESS_TYPE_VIRT_WRITE

### To Reproduce

ollama or llama.cpp using any LLM will cause the issue.

### Bug Incidence

Always

### nvidia-bug-report.log.gz

[nvidia-bug-report.log.gz](https://github.com/user-attachments/files/25397023/nvidia-bug-report.log.gz)

### More Info

reproducible on Leap15.6, archlinux, ubuntu etc...
Tried multiple 5XX.XX Nividia drivers with different kernel version, always same error.

**Comment by sempervictus** [comment]
```
[Thu Feb 19 17:09:32 2026] NVRM: Xid (PCI:0000:41:00): 31, pid=3469574, name=runner, channel 0x00000004, intr 00000000. MMU Fault: ENGINE GRAPHICS GPC2 GPCCLIENT_T1_4 faulted @ 0x4a_da000000. Fault is of type FAULT_PDE ACCESS_TYPE_VIRT_READ
[Thu Feb 19 18:04:49 2026] NVRM: Xid (PCI:0000:41:00): 31, pid=3480806, name=runner, channel 0x00000004, intr 00000000. MMU Fault: ENGINE GRAPHICS GPC5 GPCCLIENT_T1_6 faulted @ 0x4a_a4000000. Fault is of type FAULT_PDE ACCESS_TYPE_VIRT_READ
[Thu Feb 19 18:32:38 2026] NVRM: Xid (PCI:0000:41:00): 31, pid=3490436, name=runner, channel 0x00000004, intr 00000000. MMU Fault: ENGINE GRAPHICS GPC5 GPCCLIENT_T1_6 faulted @ 0x4a_ec000000. Fault is of type FAULT_PDE ACCESS_TYPE_VIRT_READ
[Thu Feb 19 18:48:09 2026] NVRM: Xid (PCI:0000:01:00): 31, pid=3493369, name=runner, channel 0x00000004, intr 00000000. MMU Fault: ENGINE GRAPHICS GPC11 GPCCLIENT_T1_13 faulted @ 0x4a_40000000. Fault is of type FAULT_PDE ACCESS_TYPE_VIRT_READ
[Thu Feb 19 19:00:06 2026] NVRM: Xid (PCI:0000:c1:00): 31, pid=3495208, name=runner, channel 0x00000004, intr 00000000. MMU Fault: ENGINE GRAPHICS GPC10 GPCCLIENT_T1_1 faulted @ 0x4a_76000000. Fault is of type FAULT_PDE ACCESS_TYPE_VIRT_READ
```
this is making it utterly impossible to work on long-context because it trips every time it gets to ~600k of prefill on a 750k chat session. Trying to see if `590.44.01` will help.

What's interesting is that NV explicitly tells CSPs on their regular video calls (we build/run clouds for some of them) to use 590 as a fix for their blackwell woes while it seems to have a bunch of instability baked-in :-\\

**Comment by Tuipveus** [comment]
I confirm same bug with Debian 13, RTX4070ti and Ollama 0.17.1, Linux ai 6.12.63+deb13-amd64.
I have observed this with only after I 
- changed my drivers from nvidia-driver to nvidia-open (both from nvidia repo) and 
- installed qwen3.5:35b-a3b
- I use long query. ( I know 245 characters is too long to trick this)
Same driver version, 590.48.01

dmesg:
[21629.222654] NVRM: Xid (PCI:0000:01:00): 31, pid=36642, name=ollama, channel 0x00000017, intr 00000000. MMU Fault: ENGINE GRAPHICS GPC3 GPCCLIENT_T1_0 faulted @ 0x7f49_91939000. Fault is of type FAULT_PDE ACCESS_TYPE_VIRT_WRITE
[21662.093157] NVRM: Xid (PCI:0000:01:00): 31, pid=37060, name=ollama, channel 0x00000011, intr 00000000. MMU Fault: ENGINE GRAPHICS GPC2 GPCCLIENT_T1_0 faulted @ 0x7f7e_e1939000. Fault is of type FAULT_PDE ACCESS_TYPE_VIRT_WRITE
[21728.129662] NVRM: Xid (PCI:0000:01:00): 31, pid=37585, name=ollama, channel 0x00000012, intr 00000000. MMU Fault: ENGINE GRAPHICS GPC3 GPCCLIENT_T1_0 faulted @ 0x7f84_43939000. Fault is of type FAULT_PDE ACCESS_TYPE_VIRT_WRITE
[21778.581869] NVRM: Xid (PCI:0000:01:00): 31, pid=38025, name=ollama, channel 0x00000011, intr 00000000. MMU Fault: ENGINE GRAPHICS GPC3 GPCCLIENT_T1_0 faulted @ 0x7fac_c7939000. Fault is of type FAULT_PDE ACCESS_TYPE_VIRT_WRITE
[21799.480313] NVRM: Xid (PCI:0000:01:00): 31, pid=38441, name=ollama, channel 0x00000015, intr 00000000. MMU Fault: ENGINE GRAPHICS GPC4 GPCCLIENT_T1_0 faulted @ 0x7ff4_3f939000. Fault is of type FAULT_PDE ACCESS_TYPE_VIRT_WRITE
[22434.435474] NVRM: Xid (PCI:0000:01:00): 31, pid=39632, name=ollama, channel 0x00000012, intr 00000000. MMU Fault: ENGINE GRAPHICS GPC0 GPCCLIENT_T1_0 faulted @ 0x7efb_82b96000. Fault is of type FAULT_PDE ACCESS_TYPE_VIRT_WRITE

**Comment by Tuipveus** [comment]
At least in my case, the problem is with line ggml-cuda.cu:438, instead of yours @aginies: ggml-cuda.cu:790.
Our similarities are "ggml-cuda.cu:94: CUDA error"

So my problem is probably a bug in Ollama, rather than Nvidia-open driver:
Bug reported and it has workaround here:
https://github.com/ollama/ollama/issues/14444

I haven't yet had time to try if that workaround works for me.

helmi 27 17:46:56 ai ollama[1141]: time=2026-02-27T17:46:56.107+02:00 level=DEBUG source=server.go:1394 msg="model load progress 0.99"
helmi 27 17:46:56 ai ollama[1141]: time=2026-02-27T17:46:56.301+02:00 level=DEBUG source=ggml.go:324 msg="key with type not found" key=qwen35moe.pooling_type default=0
helmi 27 17:46:56 ai ollama[1141]: time=2026-02-27T17:46:56.358+02:00 level=INFO source=server.go:1388 msg="llama runner started in 17.87 seconds"
helmi 27 17:46:56 ai ollama[1141]: time=2026-02-27T17:46:56.358+02:00 level=DEBUG source=sched.go:578 msg="finished setting up" runner.name=registry.ollama.ai/library/qwen3.5:35b-a3b runner.inference="[{ID:GPU->
helmi 27 17:46:56 ai ollama[1141]: time=2026-02-27T17:46:56.412+02:00 level=DEBUG source=server.go:1536 msg="completion request" images=0 prompt=292 format=""
helmi 27 17:46:56 ai ollama[1141]: time=2026-02-27T17:46:56.445+02:00 level=DEBUG source=cache.go:151 msg="loading cache slot" id=0 cache=0 prompt=83 used=0 remaining=83
helmi 27 17:46:56 ai ollama[1141]: CUDA error: invalid argument
helmi 27 17:46:56 ai ollama[1141]:   current device: 0, in function ggml_cuda_cpy at //ml/backend/ggml/ggml/src/ggml-cuda/cpy.cu:438
helmi 27 17:46:56 ai ollama[1141]:   cudaMemcpyAsyncReserve(src1_ddc, src0_ddc, ggml_nbytes(src0), cudaMemcpyDeviceToDevice, main_stream)
helmi 27 17:46:56 ai ollama[1141]: //ml/backend/ggml/ggml/src/ggml-cuda/ggml-cuda.cu:94: CUDA error
helmi 27 17:46:56 ai ollama[1141]: /usr/local/lib/ollama/libggml-base.so.0(+0x1bae8) [0x7f25e453bae8]
helmi 27 17:46:56 ai ollama[1141]: /usr/local/lib/ollama/libggml-base.so.0(ggml_print_backtrace+0x1e6) [0x7f25e453beb6]
helmi 27 17:46:56 ai ollama[1141]: /usr/local/lib/ollama/libggml-base.so.0(ggml_abort+0x11d) [0x7f25e453c03d]
helmi 27 17:46:56 ai ollama[1141]: /usr/local/lib/ollama/cuda_v13/libggml-cuda.so(+0x1585d2) [0x7f25a15585d2]
helmi 27 17:46:56 ai ollama[1141]: /usr/local/lib/ollama/cuda_v13/libggml-cuda.so(_Z13ggml_cuda_cpyR25ggml_backend_cuda_contextPK11ggml_tensorPS1_+0x5305) [0x7f25a15123f5]
helmi 27 17:46:56 ai ollama[1141]: /usr/local/lib/ollama/cuda_v13/libggml-cuda.so(+0x16855e) [0x7f25a156855e]
helmi 27 17:46:56 ai ollama[1141]: /usr/local/lib/ollama/cuda_v13/libggml-cuda.so(+0x16b79a) [0x7f25a156b79a]
helmi 27 17:46:56 ai ollama[1141]: /usr/local/lib/ollama/cuda_v13/libggml-cuda.so(+0x16d705) [0x7f25a156d705]
helmi 27 17:46:56 ai ollama[1141]: /usr/local/bin/ollama(+0x13ac156) [0x5573bd6bf156]
helmi 27 17:46:56 ai ollama[1141]: /usr/local/bin/ollama(+0x132034b) [0x5573bd63334b]
helmi 27 17:46:56 ai ollama[1141]: /usr/local/bin/ollama(+0x3ddae1) [0x5573bc6f0ae1]
helmi 27 17:46:56 ai ollama[1141]: SIGABRT: abort
helmi 27 17:46:56 ai ollama[1141]: PC=0x7f2634d8295c m=20 sigcode=18446744073709551610
helmi 27 17:46:56 ai ollama[1141]: signal arrived during cgo execution
helmi 27 17:46:56 ai ollama[1141]: goroutine 1296 gp=0xc001190000 m=20 mp=0xc00190a008 [syscall]:

**Comment by whoracle** [comment]
Getting the same issue while using UnrealEditor 5.7.4 for development. Will work for a little bit, then Vulkan will crash out, afterwards UE is unusable due to certain Windows/Modals not being drawn - even outside of the actual Project I'm developing, just inside the Project Picker. Only reboot helps. Tried disabling GSP, didn't make a difference.

```
[    2.329368] NVRM: loading NVIDIA UNIX Open Kernel Module for x86_64  595.71.05  Release Build  (root@)  
[  365.969676] NVRM: GPU at PCI:0000:01:00: GPU-4e391288-897c-ba5d-6944-dfbea55ebcfa
[  365.969680] NVRM: GPU Board Serial Number: 0
[  365.969681] NVRM: Xid (PCI:0000:01:00): 31, pid=13705, name=UnrealEditor, channel 0x0000000c, intr 00000000. MMU Fault: ENGINE GRAPHICS GPC2 GPCCLIENT_PROP_0 faulted @ 0x0_00000000. Fault is of type FAULT_PDE ACCESS_TYPE_VIRT_READ
```

Arch Linux, 7.0.5-arch1-1, nvidia-open 595.71.05-5, RTX 5070TI.
Can reproduce at will if tests are needed.

Edit: Reproducible with a 1650 Max-Q on my Laptop with the same nvidia-open version. Not reproducible (at the moment) with a RTX 3080FE.

**Comment by whoracle** [comment]
Did some testing/digging, here's what I found:

--- machine A ---
1650 nvidia driver: Works
1650 nvidia-open driver: Crashes
--- machine B ---
3080 nvidia driver: Works
3080 nvidia-open driver: Crashes
5070TI nvidia driver: not available
5070TI nvidia-open driver: Crashes

Tested with both nvidia-open current 595.71.05 and beta 610.43.02.
Tested with Unreal 5.6, 5.7 and 5.8

Also posted this to [nvidia forums](https://forums.developer.nvidia.com/t/xid-31-vulkan-crash-on-5070ti-nvidia-open-unreal-engine-5-7/370489) and opened a bug with Unreal. But it sounds like this is the most promising place.
