### ISSUE TITLE
RTX 5090 (GB202): GSP heartbeat timeout -> Xid 109/8 under Vulkan load via Proton (595.58.03, 590.48.01)

### ISSUE THREAD

**Issue by Loong0x00** [NVIDIA/open-gpu-kernel-modules#1080]
## Summary

RTX 5090 (GB202) reliably crashes under heavy Vulkan workloads (Proton games with ray tracing enabled). The root cause is **GSP firmware heartbeat timeout**, which then cascades into Xid 109 (CTX SWITCH TIMEOUT) and Xid 8. The GPU enters an unrecoverable dirty state requiring PCI Secondary Bus Reset.

This issue reproduces on both driver **590.48.01** and **595.58.03** (nvidia-open-dkms).

## Key Observation: GSP dies first, Xid 109 is a symptom

The crash sequence is always:
1. `_kgspRpcRecvPoll: GSP RM heartbeat timed out` (diff ~8000ms > timeout 5200ms)
2. `os_schedule: Attempted to yield the CPU while in atomic or interrupt context` (repeated)
3. `Xid 8` (channel error)
4. `Xid 109: CTX SWITCH TIMEOUT` (consequence, not cause)
5. `Xid 154: GPU recovery action changed to GPU Reset Required`
6. `krcWatchdog_IMPL: RC watchdog: GPU is probably locked!`
7. Eventually: `kflcnWaitForHaltRiscv_GA102: Timeout waiting for RISC-V to halt`

**Increasing `RmEngineContextSwitchTimeoutUs` from default 0x003fffff (~4.2s) to 0x01FFFFFF (~33.6s) has no effect**, confirming the issue is GSP firmware death, not a slow context switch.

## System Info

- **GPU**: NVIDIA GeForce RTX 5090 (GB202, PCI 0000:01:00.0)
- **CPU**: AMD Ryzen 9 9950X3D
- **Kernel**: 6.19.9-arch1-1 (x86_64, SMP PREEMPT_DYNAMIC)
- **Distro**: Arch Linux (rolling)
- **Driver**: nvidia-open-dkms 595.58.03 (also reproduced on 590.48.01)
- **Display**: Primary on AMD iGPU (amdgpu), NVIDIA is headless compute/gaming only
- **Workload**: Proton/Wine Vulkan game with ray tracing maxed out (`Client-Win64-Sh`)

## Module config

```
options nvidia NVreg_PreserveVideoMemoryAllocations=1
options nvidia NVreg_EnableGpuFirmware=0
options nvidia NVreg_RegistryDwords="RMUseSwI2c=0x01"
options nvidia_drm modeset=1 fbdev=1
```

Note: `NVreg_EnableGpuFirmware=0` has no effect on Blackwell (GSP is mandatory).

## dmesg (crash on 595.58.03)

```
[ 2919.058761] NVRM: krcWatchdog_IMPL: RC watchdog: GPU is probably locked!  Notify Timeout Seconds: 7
[ 2919.062118] NVRM: Xid (PCI:0000:01:00): 8, pid=24239, name=Client-Win64-Sh, channel 0x00000003
[ 2921.058779] NVRM: os_schedule: Attempted to yield the CPU while in atomic or interrupt context
[ 2923.058808] NVRM: os_schedule: Attempted to yield the CPU while in atomic or interrupt context
[ 2925.058838] NVRM: os_schedule: Attempted to yield the CPU while in atomic or interrupt context
[ 2927.058867] NVRM: os_schedule: Attempted to yield the CPU while in atomic or interrupt context
[ 2927.084007] NVRM: _kgspIsHeartbeatTimedOut: Heartbeat timed out, currentTimeMs 709957545 heartbeat 105067568 heartbeatWithOffsetMs 709949520 diff 8025 timeout 5200
[ 2927.084010] NVRM: _kgspRpcRecvPoll: GSP RM heartbeat timed out
[ 2934.711949] NVRM: Xid (PCI:0000:01:00): 109, pid=24239, name=Client-Win64-Sh, channel 0x00000003, errorString CTX SWITCH TIMEOUT, Info 0x8002
[ 2938.724106] NVRM: krcWatchdog_IMPL: RC watchdog: GPU is probably locked!  Notify Timeout Seconds: 7
[ 2946.749675] NVRM: _kgspIsHeartbeatTimedOut: Heartbeat timed out, currentTimeMs 709977211 heartbeat 105087233 heartbeatWithOffsetMs 709969185 diff 8026 timeout 5200
[ 2946.749679] NVRM: _kgspRpcRecvPoll: GSP RM heartbeat timed out
[ 3044.845809] NVRM: _kgspIsHeartbeatTimedOut: Heartbeat timed out, currentTimeMs 710075306 heartbeat 105185329 heartbeatWithOffsetMs 710067281 diff 8025 timeout 5200
[ 3044.845810] NVRM: _kgspRpcRecvPoll: GSP RM heartbeat timed out
[ 3152.390871] NVRM: kflcnWaitForHaltRiscv_GA102: Timeout waiting for RISC-V to halt
[ 3152.390889] NVRM: nvAssertFailedNoLog: Assertion failed: rmStatus == NV_OK @ osinit.c:2501
```

## dmesg (crash on 590.48.01, same pattern)

```
[ 1345.496354] NVRM: GPU0 _kgspRpcRecvPoll: GSP RM heartbeat timed out
[ 1349.792770] NVRM: Xid (PCI:0000:01:00): 109, pid=20516, name=Client-Win64-Sh, channel 0x00000003, errorString CTX SWITCH TIMEOUT, Info 0x8002
[ 1354.091939] NVRM: Xid (PCI:0000:01:00): 109, pid=20516, name=Client-Win64-Sh, channel 0x00000003, errorString CTX SWITCH TIMEOUT, Info 0x8002
[ 1358.104312] NVRM: Xid (PCI:0000:01:00): 8, pid=20516, name=Client-Win64-Sh, channel 0x00000004
[ 1366.117440] NVRM: _kgspIsHeartbeatTimedOut: Heartbeat timed out, currentTimeMs 703942760 heartbeat 99052772 heartbeatWithOffsetMs 703934745 diff 8015 timeout 5200
[ 1366.117443] NVRM: _kgspRpcRecvPoll: GSP RM heartbeat timed out
```

## Recovery workaround

Standard `nvidia-smi --gpu-reset` is deprecated (570+). PCI device reset (`echo 1 > .../reset`) fails because WPR2 region remains active. The only working recovery without reboot is **Secondary Bus Reset** via upstream PCI bridge:

```bash
# 1. Kill all GPU users, stop services
# 2. Remove PCI device
echo 1 > /sys/bus/pci/devices/0000:01:00.0/remove
# 3. Unload all nvidia modules
modprobe -r nvidia_drm nvidia_uvm nvidia_modeset nvidia
# 4. Secondary Bus Reset on upstream bridge
setpci -s 00:01.1 BRIDGE_CONTROL.w=0040:0040; sleep 1
setpci -s 00:01.1 BRIDGE_CONTROL.w=0000:0040; sleep 3
# 5. PCI rescan + reload modules
echo 1 > /sys/bus/pci/rescan; sleep 3
modprobe nvidia nvidia_modeset nvidia_drm nvidia_uvm
```

Without SBR, reloading the driver fails with:
```
NVRM: GPU0 _kgspBootGspRm: unexpected WPR2 already up, cannot proceed with booting GSP
NVRM: GPU0 _kgspBootGspRm: (the GPU is likely in a bad state and may need to be reset)
```

## Related issues

- #1045 (RTX 5080, Xid 119 GSP timeout on Arch Linux)
- #1057 (NVIDIA GSP I2C bug on Blackwell)

**Comment by Loong0x00** [comment]
## Firmware RE Analysis: The root cause is missing GPU Reset Recovery on Blackwell

After reverse-engineering the GSP firmware (`gsp_ga10x.bin`, 595.58.03), I found that the GSP behavior is **by design** — the actual bug is in the kernel driver's recovery path.

### What happens inside GSP firmware

The firmware contains a graphics engine hung handler at offset `0x5c38d0` in the `.fwimage` section. When FECS (Front End Context Switch) falcon detects that a graphics engine failed to complete a context switch within the timeout:

1. The handler checks the error type (`addiw a4, a0, -22`)
2. For types 22/23: special handling with logging and notification
3. **For all other types**: prints `"Graphics Exception on BE %d: Graphics is hung, FATAL!!"`, then executes:

\`\`\`asm
0x005c392e      ebreak              ; trap to debug monitor
0x005c3930      j 0x5c3930          ; infinite loop (halt)
\`\`\`

Even the \`RmGspHaltOnRC\` alternate path (at \`0x5c3948\`) ends with \`ebreak\` at \`0x005c397c\`.

**This is standard embedded firmware design** — halt on unrecoverable error, wait for external reset. The GSP is doing exactly what it should: "I detected a fatal hardware condition, I'm stopping to prevent further damage, please reset me."

### Where it actually breaks

The intended recovery flow:
\`\`\`
Engine hung -> GSP detects -> GSP halts (ebreak)
-> Kernel driver detects no heartbeat -> Xid 154 (GPU Reset Required)  
-> Driver performs full GPU reset (clear WPR2, reload GSP firmware)
-> GPU returns to clean state -> User process crashes but GPU is usable
\`\`\`

**The kernel driver never performs the actual GPU reset.** After Xid 154, it just loops printing \`krcWatchdog_IMPL: RC watchdog: GPU is probably locked!\` every 7 seconds forever. The reset recovery path for Blackwell is either not implemented or broken.

Evidence: when I manually perform the equivalent reset from userspace (PCI remove -> module unload -> Secondary Bus Reset via upstream bridge -> PCI rescan -> module reload), the GPU recovers perfectly. The driver's own attempt to re-initialize without SBR fails with:

\`\`\`
NVRM: GPU0 _kgspBootGspRm: unexpected WPR2 already up, cannot proceed with booting GSP
\`\`\`

This confirms the driver knows it needs to clear WPR2 but doesn't do it. On older architectures (Turing/Ampere/Ada), GPU reset could work without clearing WPR2. On Blackwell, GSP uses a new secure boot flow where WPR2 must be torn down via a proper hardware reset before GSP can be re-initialized.

### Firmware structure notes

For anyone investigating further:
- The firmware is a 69MB RISC-V ELF with multiple embedded ELF partitions (at offsets 0x6e000, 0x95000, 0xbd000, etc.)
- Source paths are embedded: libos-v3.1.0 (kernel scheduler, heartbeat, DMA, etc.)
- Key strings: RmEngineContextSwitchTimeoutUs, RmGspHaltOnRC, RmGspLibosWatchdogTimeOut
- The heartbeat code is at libos-v3.1.0/kernel/full/sched/heartbeat.c
- 10 .fwsignature sections = firmware is cryptographically signed, cannot be patched

### Summary

| Component | Behavior | Correct? |
|---|---|---|
| GPU graphics engine | Hangs under heavy RT load | Hardware limitation (not a bug) |
| FECS falcon | Detects hung engine, reports to GSP | Working as designed |
| GSP firmware | Halts with ebreak + infinite loop | Working as designed |
| **Kernel driver (GPU reset)** | **Detects Xid 154 but never resets GPU** | **Bug: recovery not implemented for Blackwell** |

The fix should be in the kernel driver's GPU reset path — specifically, it needs to perform a Secondary Bus Reset (or equivalent) to clear WPR2 before re-initializing GSP on Blackwell GPUs.

**Comment by wallter** [comment]
### Cross-reference: Captured the thermal trigger for this crash pattern (RTX PRO 6000)

I've been tracking the same underlying Blackwell GSP crash on an RTX PRO 6000 (GB202GL) in #1045. Captured the exact moment of GPU death at 100ms resolution using NVML telemetry. The data may explain **what triggers the GSP crash** that your firmware RE analysis describes:

| time | temp | power | fan0 | throttle | |
|------|------|-------|------|----------|-|
| 11:26:34.2 | **92C** | 566W | 53% | SwPowerCap | 1C from GPU max, fans not responding |
| 11:26:36.3 | **92C** | 549W | 56% | **SwThermalSlowdown** | thermal throttle finally fires |
| 11:26:37.5 | 88C | 538W | 74% | SwPowerCap | fans ramping — too late |
| 11:26:38.2 | 88C | **570W** | 90% | None | last good reading |
| **11:26:38.3** | **92C** | 570W | **0%** | SwPowerCap | **Xid 79 → PCIe x16→x0, GPU dead** |

The **fan controller doesn't respond to 92C** (1C from the 93C GPU max). When it finally starts ramping at 11:26:36.7, the GSP crashes < 2 seconds later. The Xid 154 recovery action was **0x2 (Node Reboot Required)** — consistent with your finding that the kernel driver can't execute a proper reset on Blackwell because it can't clear WPR2.

Session stats before crash: 2,888 fan-temperature inversions (>85C with fans <55%), peak 93C, peak 601W, 422 power limit breaches. The fan controller's firmware target is 30% while actual is 53% — it's overriding itself but not nearly enough.

This suggests the GSP crash is a **thermal fault triggered by broken fan firmware**, not a random GSP failure. The fan controller lets the GPU approach thermal limits, the GSP hits its thermal fault handler (the `ebreak` you found at offset `0x5c38d0`), and the missing recovery path means the GPU dies permanently until PSU power cycle.

Telemetry script that captured this: [gpu-telemetry-deep.py](https://gist.github.com/wallter/4c60d1a6607defde7a0fd87709ae9ee0). Full crash details in #1045.

**Comment by Loong0x00** [comment]
### Confirming hardware-independence: same silicon, two different triggers

@wallter Your data is exactly what this issue needed. To make the convergence explicit:

| Card | Die | Trigger | Failure path | Recovery in driver |
|---|---|---|---|---|
| RTX 5090 (mine) | **GB202-300-A1** | Undervolt + clock offset, transient instability around 3000 MHz | GSP heartbeat timeout → Xid 109 → Xid 154 | None — driver loops on RC watchdog |
| RTX PRO 6000 (yours) | **GB202GL** (same die, workstation bin) | Fan firmware fails to ramp, sustained 92 °C | SwThermalSlowdown (too late) → Xid 79 → Xid 154 | None — PSU power cycle required |

**Same physical silicon, two completely independent trigger conditions, identical fatal code path in firmware, identical kernel-driver failure to recover.** This removes the usual deflection narratives:

- "User overclocked / undervolted" — your card is stock
- "Inadequate cooling" — my card never exceeded 75 °C when it crashed
- "Consumer-card specific" — RTX PRO 6000 is an $8k+ workstation card

The common factor is **GB202 + the current driver's missing Blackwell GPU reset path**, not anything about the trigger.

### Re: thermal fault handler — it's actually the same code path

You hypothesized the GSP hits a separate thermal fault handler that ends in `ebreak`. I went back into `gsp_ga10x.bin` (595.58.03) to verify, and the result is more interesting than two independent handlers:

- The only `_THERMAL_` string in the firmware is `NETIR_THERMAL_EVENT`, which belongs to the NVLink switch subsystem (NETIR = Network Error Interrupt Routing) — **not** GPU die temperature.
- There are no `TSENSE` or GPU temp-sensor strings in the firmware at all.
- All graphics-engine "FATAL" strings (`Graphics is hung, FATAL!!` on BE, GPC CROP, GPC ZROP, plus `Graphics FECS Exception: UCODE Fatal Error`) trace back to the same handler region around `0x5c38d0`.

Die temperature is handled **RM-side** via clock slowdown (`RMClkSlowDown`, `EnableMClkSlowdown`) — that's the `SwThermalSlowdown` you captured at 11:26:36.3, which is the kernel driver trying to save itself, not GSP firmware.

So your crash chain is almost certainly:

```
sustained ~92 °C
  → RM SwThermalSlowdown triggers (too late, fan firmware broken)
  → graphics engine clocks can't keep up / register state corrupts
  → FECS detects "graphics didn't make context-switch deadline"
  → GSP receives FECS exception
  → enters the SAME 0x5c38d0 handler as my undervolt crashes
  → ebreak + infinite loop, waiting for an external reset that never comes
```

This is a **stronger** finding than two independent ebreak paths. It means: **regardless of trigger — undervolt instability, thermal stall, or anything else that makes the graphics engine miss its context-switch deadline — every GB202 graphics-engine fatal converges into one fatal path that assumes the kernel driver will perform a GPU reset.** The firmware's design contract is correct; the driver's failure to honor it turns every transient stall into a permanent brick.

So the missing recovery path is more critical than it looked at first: it's not one corner case, it's the **single failure mode** for an entire class of graphics-engine faults on Blackwell.

### Userspace recovery without PSU power cycle

You mentioned the PRO 6000 dies until a PSU power cycle. On the 5090 I can fully recover from Xid 109/154 in userspace via Secondary Bus Reset:

https://gist.github.com/Loong0x00/a3683af55a40fc4fd8a5740055342697

The script auto-detects the GPU and its upstream PCIe bridge from sysfs, so you don't need to know the bridge address ahead of time. Core sequence:

1. Stop GPU consumers, unload all `nvidia*` kernel modules
2. Secondary Bus Reset on the upstream bridge (`setpci -s <bridge> BRIDGE_CONTROL.w=0040:0040` then `0000:0040`)
3. `echo 1 > /sys/bus/pci/rescan`
4. Reload `nvidia` modules

After this, `nvidia-smi` returns clean and the GPU is usable again. No reboot, no PSU cycle.

**Caveat for workstation users without iGPU:** my recovery works because my AM5 system has an iGPU handling the desktop, so nothing holds `nvidia_drm` and I can `modprobe -r` it cleanly. On a typical workstation (Threadripper / Xeon, no iGPU, display on the NVIDIA card), you'd need to drop to a TTY and `systemctl stop gdm` first — at which point the convenience advantage over rebooting mostly evaporates. The technical point still stands though: **if userspace can perform SBR + WPR2 clear + GSP reload, the kernel driver has no architectural excuse not to do the same thing internally.**

If you do try this on the PRO 6000, the most informative datapoint would be: does the userspace SBR successfully clear WPR2 on a workstation-bin GB202, or does that path also fail? If it works, that's the final nail — same silicon, same firmware, same recovery primitive that the driver refuses to use.

### Summary of evidence so far

- Two independent crash reports on GB202 (consumer and workstation bins)
- Two completely different trigger conditions converging to one firmware fatal handler
- Firmware RE confirms the halt is by design, waiting for external reset
- Userspace SBR recovers the GPU on at least the consumer card

This is unambiguously a kernel-driver bug. The driver needs to:

1. Detect Xid 154 / GSP heartbeat loss
2. Perform Secondary Bus Reset (or equivalent) on the GPU
3. Clear the WPR2 region
4. Reload GSP firmware via the normal init path

All four steps work from userspace today. There is no architectural reason the driver cannot do them.

**Comment by wallter** [comment]
@Loong0x00 Have been running for 12+hrs full TDP overriding the fans -- go figure if you prevent the card(s) from hitting the thermal shutdown ceiling they don't cause a crash -- via; [gpu-fan-control.py](https://gist.github.com/wallter/285e4d01284202b9f04dd554c470cafb)

That script also has controls for case fans if you want to scale them per GPU temp to dissipate heat. Seeing a -20C temp (~70C) under load vs 85C+ without the script.

**Comment by oxynaz** [comment]
Reproducing on dual RTX 5090 under LLM inference (llama.cpp, not Vulkan)
System:

GPU: 2× NVIDIA GeForce RTX 5090 (GB202)
CPU: AMD Ryzen 9 9900X (no iGPU)
OS: Debian 12, Kernel: 6.12
Driver: nvidia-open 595.58.03 (also reproduced on 580.x)
Workload: llama.cpp (turboquant fork, SM120) serving Qwen3-Coder-Next Q6_K GGUF at 262K context

Crash pattern:
Same fatal path as reported. GPU0 (0000:01:00.0) dies under sustained CUDA inference load. GPU1 (0000:02:00.0) remains fully functional. System stays alive (no hard freeze).
Not thermal: GPU temperatures were 50-57°C at crash time. This is purely a GSP failure under sustained CUDA compute load, not thermal shutdown.
dmesg signature: identical — GspRmFree failed status=0x0000000f cascade, no heartbeat timeout messages preceding the crash (GSP dies abruptly, not progressively).
Recovery attempt: Secondary Bus Reset via upstream bridge (00:01.1) did NOT recover GPU0. modprobe -r nvidia completed but GPU0 remained invisible to nvidia-smi. Full reboot required.
Confirmation of your firmware RE analysis: the missing Blackwell GPU reset path in the kernel driver is the root issue. The trigger (Vulkan RT, LLM inference, or any sustained compute) is irrelevant — the recovery path is simply absent.

**Comment by vjureta** [comment]
Filed #1111  — appears to be a silent-hang variant of the same GB202 GSP firmware death class you're seeing, but under sustained LLM inference (llama.cpp + Qwen3-32B) rather than Vulkan/Proton. No Xid raised at all in my case, which is the distinguishing signature.

**Comment by es20490446e** [comment]
My system:
- Zenned OS
- Linux Zen
- KDE Plasma Wayland

The issue doesn't happen on:
- 590.48.01

But it does on:
- 595.58.03
- 595.71.05

My questions:
- Why having versions with different levels of support or stability?
- Why not just having one, and reverting any breaking change as soon as discovered?
- Why two months with unusable drivers?
- Why publishing further broken releases?
- Does the semantic versioning even make sense here?

**Comment by EthanGraber** [comment]
I tried downgrading to 590.48 after @es20490446e 's comment, still was able to reproduce the issue. I've crashed on the latest 595.x versions as well, which is what led me to this thread in the first place. 

My most recent crash logs if they're of any interest, it's roughly the same every time:

```
➜ ~ journalctl -b -1 --no-pager | grep -iE "gpu|drm|amdgpu|nvidia|nouveau|hang|reset|error" | tail -50
May 02 21:43:54 ethan-desktop kernel: NVRM: nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status == NV_ERR_GPU_IN_FULLCHIP_RESET) @ rs_server.c:1375
May 02 21:43:54 ethan-desktop kernel: NVRM: GPU0 _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 10 sequence 12303!
May 02 21:43:54 ethan-desktop kernel: NVRM: GPU0 rpcRmApiFree_GSP: GspRmFree failed: hClient=0xc1d00029; hObject=0xbeef0100; paramsStatus=0x00000000; status=0x0000000f
May 02 21:43:54 ethan-desktop kernel: NVRM: GPU0 _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 10 sequence 12304!
May 02 21:43:54 ethan-desktop kernel: NVRM: GPU0 rpcRmApiFree_GSP: GspRmFree failed: hClient=0xc1d00029; hObject=0xcef00000; paramsStatus=0x00000000; status=0x0000000f
May 02 21:43:54 ethan-desktop kernel: NVRM: GPU0 nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status == NV_ERR_GPU_IN_FULLCHIP_RESET) @ rs_client.c:844
May 02 21:43:54 ethan-desktop kernel: NVRM: nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status == NV_ERR_GPU_IN_FULLCHIP_RESET) @ rs_server.c:259
May 02 21:43:54 ethan-desktop kernel: NVRM: nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status == NV_ERR_GPU_IN_FULLCHIP_RESET) @ rs_server.c:1375
May 02 21:43:54 ethan-desktop kernel: NVRM: GPU0 _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 10 sequence 12305!
May 02 21:43:54 ethan-desktop kernel: NVRM: GPU0 rpcRmApiFree_GSP: GspRmFree failed: hClient=0xc1d00029; hObject=0xcef80000; paramsStatus=0x00000000; status=0x0000000f
May 02 21:43:54 ethan-desktop kernel: NVRM: GPU0 nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status == NV_ERR_GPU_IN_FULLCHIP_RESET) @ rs_client.c:844
May 02 21:43:54 ethan-desktop kernel: NVRM: nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status == NV_ERR_GPU_IN_FULLCHIP_RESET) @ rs_server.c:259
May 02 21:43:54 ethan-desktop kernel: NVRM: nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status == NV_ERR_GPU_IN_FULLCHIP_RESET) @ rs_server.c:1375
May 02 21:43:54 ethan-desktop kernel: NVRM: GPU0 _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 10 sequence 12306!
May 02 21:43:54 ethan-desktop kernel: NVRM: GPU0 rpcRmApiFree_GSP: GspRmFree failed: hClient=0xc1d00029; hObject=0xcef80001; paramsStatus=0x00000000; status=0x0000000f
May 02 21:43:54 ethan-desktop kernel: NVRM: GPU0 nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status == NV_ERR_GPU_IN_FULLCHIP_RESET) @ rs_client.c:844
May 02 21:43:54 ethan-desktop kernel: NVRM: nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status == NV_ERR_GPU_IN_FULLCHIP_RESET) @ rs_server.c:259
May 02 21:43:54 ethan-desktop kernel: NVRM: nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status == NV_ERR_GPU_IN_FULLCHIP_RESET) @ rs_server.c:1375
May 02 21:43:54 ethan-desktop kernel: NVRM: GPU0 _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 10 sequence 12307!
May 02 21:43:54 ethan-desktop kernel: NVRM: GPU0 rpcRmApiFree_GSP: GspRmFree failed: hClient=0xc1d00029; hObject=0xbeef0202; paramsStatus=0x00000000; status=0x0000000f
May 02 21:43:54 ethan-desktop kernel: NVRM: GPU0 nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status == NV_ERR_GPU_IN_FULLCHIP_RESET) @ mem.c:178
May 02 21:43:54 ethan-desktop kernel: NVRM: GPU0 _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 10 sequence 12308!
May 02 21:43:54 ethan-desktop kernel: NVRM: GPU0 rpcRmApiFree_GSP: GspRmFree failed: hClient=0xc1d00029; hObject=0xbeef0300; paramsStatus=0x00000000; status=0x0000000f
May 02 21:43:54 ethan-desktop kernel: NVRM: GPU0 nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status == NV_ERR_GPU_IN_FULLCHIP_RESET) @ vaspace_api.c:573
May 02 21:43:54 ethan-desktop kernel: NVRM: GPU0 _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 10 sequence 12309!
May 02 21:43:54 ethan-desktop kernel: NVRM: GPU0 rpcRmApiFree_GSP: GspRmFree failed: hClient=0xc1d00029; hObject=0xbeef0013; paramsStatus=0x00000000; status=0x0000000f
May 02 21:43:54 ethan-desktop kernel: NVRM: GPU0 nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status == NV_ERR_GPU_IN_FULLCHIP_RESET) @ mem.c:178
May 02 21:43:54 ethan-desktop kernel: NVRM: GPU0 _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 10 sequence 12310!
May 02 21:43:54 ethan-desktop kernel: NVRM: GPU0 rpcRmApiFree_GSP: GspRmFree failed: hClient=0xc1e00005; hObject=0xcaf00007; paramsStatus=0x00000000; status=0x0000000f
May 02 21:43:54 ethan-desktop kernel: NVRM: GPU0 _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 10 sequence 12311!
May 02 21:43:54 ethan-desktop kernel: NVRM: GPU0 rpcRmApiFree_GSP: GspRmFree failed: hClient=0xc1e00005; hObject=0xcaf00008; paramsStatus=0x00000000; status=0x0000000f
May 02 21:43:54 ethan-desktop kernel: NVRM: GPU0 _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 10 sequence 12312!
May 02 21:43:54 ethan-desktop kernel: NVRM: GPU0 rpcRmApiFree_GSP: GspRmFree failed: hClient=0xc1e00005; hObject=0xcaf00009; paramsStatus=0x00000000; status=0x0000000f
May 02 21:43:54 ethan-desktop kernel: NVRM: GPU0 _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 10 sequence 12313!
May 02 21:43:54 ethan-desktop kernel: NVRM: GPU0 rpcRmApiFree_GSP: GspRmFree failed: hClient=0xc1d00029; hObject=0xbeef0404; paramsStatus=0x00000000; status=0x0000000f
May 02 21:43:54 ethan-desktop kernel: NVRM: GPU0 _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 10 sequence 12314!
May 02 21:43:54 ethan-desktop kernel: NVRM: GPU0 rpcRmApiFree_GSP: GspRmFree failed: hClient=0xc1d00029; hObject=0xbeef9960; paramsStatus=0x00000000; status=0x0000000f
May 02 21:43:54 ethan-desktop kernel: NVRM: GPU0 nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status == NV_ERR_GPU_IN_FULLCHIP_RESET) @ rs_client.c:844
May 02 21:43:54 ethan-desktop kernel: NVRM: nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status == NV_ERR_GPU_IN_FULLCHIP_RESET) @ rs_server.c:259
May 02 21:43:54 ethan-desktop kernel: NVRM: nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status == NV_ERR_GPU_IN_FULLCHIP_RESET) @ rs_server.c:1375
May 02 21:43:54 ethan-desktop kernel: NVRM: GPU0 _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 10 sequence 12315!
May 02 21:43:54 ethan-desktop kernel: NVRM: GPU0 rpcRmApiFree_GSP: GspRmFree failed: hClient=0xc1d00029; hObject=0xbeef0004; paramsStatus=0x00000000; status=0x0000000f
May 02 21:43:54 ethan-desktop kernel: NVRM: GPU0 _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 10 sequence 12316!
May 02 21:43:54 ethan-desktop kernel: NVRM: GPU0 rpcRmApiFree_GSP: GspRmFree failed: hClient=0xc1d00029; hObject=0xbeef0073; paramsStatus=0x00000000; status=0x0000000f
May 02 21:43:54 ethan-desktop kernel: NVRM: GPU0 nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status == NV_ERR_GPU_IN_FULLCHIP_RESET) @ rs_client.c:844
May 02 21:43:54 ethan-desktop kernel: NVRM: nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status == NV_ERR_GPU_IN_FULLCHIP_RESET) @ rs_server.c:259
May 02 21:43:54 ethan-desktop kernel: NVRM: nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status == NV_ERR_GPU_IN_FULLCHIP_RESET) @ rs_server.c:1375
May 02 21:43:54 ethan-desktop kernel: NVRM: GPU0 _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 10 sequence 12317!
May 02 21:43:54 ethan-desktop kernel: NVRM: GPU0 rpcRmApiFree_GSP: GspRmFree failed: hClient=0xc1d00029; hObject=0xbeef0003; paramsStatus=0x00000000; status=0x0000000f
May 02 21:43:54 ethan-desktop kwin_wayland[10972]: No backend specified, automatically choosing drm
```

I do notice that the issue appears correlated with higher core temps, but I _have_ also crashed while the GPU is in the 60-70C range.

**Comment by CosmicBara** [comment]
I am experiencing this crash when starting Ghost of Tsushima Director's Cut. Once all of the intro videos play, as soon as I get to the main menu (sword in the ground, with a popup asking about collecting data), the game freezes (though I can still hear audio). Rest of the OS is fine (I can Alt+Tab and close out Ghost of Tsushima from System Monitor or Steam).

I tried various Proton versions, including 9.0.4, Experimental, and GE-Proton10-34 with no luck.

I'm running up-to-date Bazzite with NVIDIA GeForce RTX 5090, driver version 595.71.05.

When the freeze occurs, the command `sudo dmesg | tail -30` gives me this among other results:
[ 2651.368510] NVRM: Xid (PCI:0000:01:00): 109, pid=12998, name=GhostOfTsushima, channel 0x0000001a, errorString CTX SWITCH TIMEOUT, Info 0x1bc016

Is there anything else I can try? Or do I have to wait for a new Nvidia driver to release?

**Comment by CosmicBara** [comment]
Switching to Proton 8.0-5 fixed it for me!

**Comment by aligningmyself** [comment]
Had same issue with  Elden Ring, Xid 109, 595.58.03, fixed by downgrade to 580.159.03 on RTX 5090

**Comment by ndizazzo** [comment]
@Loong0x00 Thanks for this - it helped me do some detailed capture and analysis... you were able to help find the outcome, but I wasn't sure why the GSP was getting into a state where a WPR2 reset was needed to begin with... I did many trial runs capturing as much data as I could and had an LLM help me form a hypothesis after tweaking as many independent variables as I could.

Are you able to confirm any of these findings?

---

**RTX 5090 (GB202) — GSP TLB Invalidation Queue Deadlock Under Sustained Load**

The GSP firmware's TLB invalidation queue deadlocks under sustained GPU load. The GSP schedules ~1,750 TLB invalidations/minute during normal VA space management. One eventually fails to complete (a prior invalidation gets stuck in the GPU's TLB hardware pipeline with status `NV_ERR_STATE_IN_USE`), the queue fills to capacity, the MMU pipeline deadlocks, and the GSP firmware itself becomes unresponsive because its own Resource Manager calls depend on MMU operations. The kernel driver then detects a heartbeat timeout and reports Xid 79 ("GPU has fallen off the bus").

The crash timer (~21 minutes under 400W gaming load) is invariant. It does not change with temperature, case airflow, BIOS version, PCIe generation, or secondary GPU presence. This rules out thermal, power, and motherboard compatibility theories. The accumulation is purely internal to the GSP firmware / TLB hardware pipeline.

---

**One-sentence bug:**

```
kgmmuInvalidateTlb_GM107: TLB invalidation failed waiting for prior invalidate (status=0x0000000f)
```

This is the first hardware-level failure in every crash. Everything after it (MMU walk failure, GSP RPC collapse, Xid 79) is downstream.

---

**The crash cascade (from dmesg, nvidia-open 595.x)**

```
Step 1 - TLB pipeline stalls:
  kgmmuInvalidateTlb_GM107: TLB invalidation failed waiting for prior invalidate (status=0x0000000f)

Step 2 - MMU operations cascade-fail:
  mmuWalkUnmap: Failed to unmap VA Range [0x4ea0000-0x509ffff] Status = 0x00000040
  mmuWalkUnmap: Failed to unmap VA Range [0xf400000-0xf5fffff] Status = 0x00000040
  mmuWalkUnmap: Failed to unmap VA Range [0xa800000-0xe7fffff] Status = 0x00000040 (64MB!)
  mmu_walk_unmap.c:62: assertion failed 0 [NV_ERR_INVALID_STATE]
  Page table walks return NULL (pEntries != NULL @ gmmu_walk.c:842)
  dmaFreeMapping: error updating VA space

Step 3 - GPU sanity check fails (45+ repeated):
  API_GPU_ATTACHED_SANITY_CHECK failed!

Step 4 - Xid 79 triggered by any monitoring query:
  NVRM: Xid (PCI:0000:01:00): 79, GPU has fallen off the bus.
  Triggering process: coolercontrol (PID 11879) or nvidia-smi (PID 17124)

Step 5 - All GSP RPCs fail:
  rpcSendMessage failed with status 0x0000000f
  GspRmAlloc failed: paramsStatus=0x00000000; status=0x0000000f

Step 6 - Crash dump itself fails:
  RmLogGpuCrash: failed to save GPU crash data
```

---

**Pre-crash kernel log is completely silent**

Both captured crashes show zero NVRM messages, zero Xid errors, zero PCIe AER events, zero kernel warnings from boot until the crash instant. The longest gap: 34 minutes of silence (21:50:48 → 22:24:55). The state accumulation is invisible to the kernel driver.

---

**RPC sequence count rules out a counter overflow**

| Crash | Uptime at crash | GSP RPC sequences | Rate | Trigger |
|---|---|---|---|---|
| Fast crash (~2 min) | ~12 min | ~21,000 | ~1,750/min | nvidia-smi query |
| Slow crash (100% fans) | ~34 min | ~60,000 | ~1,750/min | coolercontrol query |

The RPC rate is stable at ~1,750 calls/min (~29/sec) regardless of runtime. The crash happens at different sequence counts (21K vs 60K), ruling out a simple call counter overflow. The TLB invalidation queue fills at a rate proportional to workload activity.

---

**Crash timer is invariant under all tested conditions**

Tested variables that did NOT change the ~21-minute crash window under 400W sustained gaming:

| Variable | Tested values | Effect on crash timer |
|---|---|---|
| Secondary GPU | RTX 3080 present / removed | None |
| Case fan speed | Default / 100% all fans | None |
| PCIe generation | Gen4 / Gen5 | None |
| BIOS version | F19 | None |
| Display config | Single monitor / headless | None |
| CPU | Intel (stable) | None |

---

**Thermal theories eliminated**

- GPU is watercooled — max die temp 55°C under 400W load
- No GPU fan exhaust to heat chipset or motherboard components
- 100% case fans did not extend crash timer
- The under-card fan workaround (helps other users by cooling the chipset) does not apply here

---

**Same TLB pattern on RTX 3070 Ti**

A report from an RTX 3070 Ti user shows the identical `kgmmuInvalidateTlb_GM107` failure, followed by the same MMU walk cascade, GPU sanity failure, and pageflip timeout loop. This suggests the TLB invalidation queue issue is a general GPU MMU characteristic, not specific to GB202. It may be exposed more aggressively on Blackwell due to higher throughput and power draw.

---

**Relationship to Loong0x00's firmware RE analysis**

Loong0x00 (issue #1080) reverse-engineered `gsp_ga10x.bin` (595.58.03) and found:
- The GSP firmware correctly detects the graphics engine hang via FECS falcon
- It enters its engine hung handler and halts (ebreak) as designed
- The kernel driver never performs the actual GPU reset on Blackwell — after detecting Xid 154, it loops printing watchdog messages instead of clearing WPR2 and re-initializing GSP
- Manual Secondary Bus Reset (PCI remove → SBR → rescan) successfully recovers the GPU

The TLB analysis here answers the question their RE raises: why does the graphics engine hang in the first place? The TLB invalidation queue deadlock stalls the MMU pipeline, which prevents the GSP's RM from functioning, which causes the graphics engine context switch to time out. The FECS falcon then correctly triggers the engine hung handler.

```
[TLB queue fills] → [MMU deadlock] → [GSP RM unresponsive]   ← our finding (trigger)
                                         ↓
[FECS detects hang] → [GSP halts (ebreak)]                     ← Loong0x00's finding (correct behavior)
                                         ↓
[Kernel detects heartbeat timeout] → [Xid 79/154]
                                         ↓
[Kernel driver never resets Blackwell (WPR2 not cleared)]     ← Loong0x00's finding (driver bug)
                                         ↓
[Hard reboot required]
```

---

**Proposed fixes**

For NVIDIA:
1. Fix GPU reset path for Blackwell — after Xid 154, perform full GPU reset including WPR2 clear and GSP firmware reload
2. Fix GSP TLB invalidation — investigate why invalidations stall (status 0xf = `NV_ERR_STATE_IN_USE`), consider adding a hardware timeout or queue flush for stuck TLB operations
3. Add pre-crash GSP diagnostics — expose GSP-internal counters (TLB queue depth, pending invalidation count) via debugfs or NVRM sysfs

For users:
- Recovery without reboot (SBR script by Loong0x00): PCI remove → module unload → SBR via upstream bridge → PCI rescan → module reload
- Lower power limit (`nvidia-smi -pl 300`) extends crash timer proportionally
- `NVreg_EnableGpuFirmware=0` has no effect on Blackwell — GSP is mandatory

---

**System config**

| Component | Detail |
|---|---|
| GPU | ASUS TUF RTX 5090 (GB202) |
| Cooling | Water block (max die temp 55°C at 400W) |
| CPU | Intel |
| Motherboard | Gigabyte Z790 (BIOS F19) |
| RAM | 64GB DDR5 |
| PSU | 1200W |
| OS | Arch Linux (rolling), kernel 6.14+ |
| Driver | nvidia-open-dkms 595.x (also tested on 590.x, 580.x) |
| Workload | CUDA inference, Vulkan gaming via Proton at 400W sustained |

---

**LLM breadcrumbs — grep for these in dmesg:**

```
kgmmuInvalidateTlb_GM107: TLB invalidation failed waiting for prior invalidate   ← smoking gun
mmuWalkUnmap: Failed to unmap VA Range                                            ← MMU cascade
mmu_walk_unmap.c:62: assertion failed 0                                           ← MMU deadlock
pEntries != NULL @ gmmu_walk.c:842                                                ← page walk failure
API_GPU_ATTACHED_SANITY_CHECK failed                                              ← GPU unresponsive
rpcSendMessage failed with status 0x0000000f                                      ← GSP collapse
GspRmAlloc failed                                                                  ← GSP collapse
_kgspRpcRecvPoll: GSP RM heartbeat timed out                                      ← GSP timeout
Xid (PCI:): 79, GPU has fallen off the bus                                        ← final outcome
RmLogGpuCrash: failed to save GPU crash data                                       ← GPU too dead to log
```

Pattern signature: if the first error is `kgmmuInvalidateTlb_GM107` followed by MMU walk failures, then GSP heartbeat timeout, then Xid 79 — this is the TLB queue deadlock variant. If dmesg starts with `GSP RM heartbeat timed out` without the TLB precursor, different trigger path (AGESA timing, thermal, power).

---

**References**

- Issue #1080 (primary): https://github.com/NVIDIA/open-gpu-kernel-modules/issues/1080
- SBR recovery gist by Loong0x00: https://gist.github.com/Loong0x00
- Issue #1045 (RTX 5080, similar pattern): https://github.com/NVIDIA/open-gpu-kernel-modules/issues/1045
- Dev Forum #366352 (RTX 5090 GSP timeout under Vulkan): https://forums.developer.nvidia.com/t/366352
- Dev Forum #369440 (AGESA correlation / thermal investigation): https://forums.developer.nvidia.com/t/369440
- RTX 3070 Ti same TLB error (not Blackwell-specific): https://forums.developer.nvidia.com/t/372569

**Comment by gengchaogit** [comment]
> Standard `nvidia-smi --gpu-reset` is deprecated (570+). PCI device reset (`echo 1 > .../reset`) fails because WPR2 region remains active. The only working recovery without reboot is **Secondary Bus Reset** via upstream PCI bridge:
> 
> # 1. Kill all GPU users, stop services
> # 2. Remove PCI device
> echo 1 > /sys/bus/pci/devices/0000:01:00.0/remove
> # 3. Unload all nvidia modules
> modprobe -r nvidia_drm nvidia_uvm nvidia_modeset nvidia
> # 4. Secondary Bus Reset on upstream bridge
> setpci -s 00:01.1 BRIDGE_CONTROL.w=0040:0040; sleep 1
> setpci -s 00:01.1 BRIDGE_CONTROL.w=0000:0040; sleep 3
> # 5. PCI rescan + reload modules
> echo 1 > /sys/bus/pci/rescan; sleep 3
> modprobe nvidia nvidia_modeset nvidia_drm nvidia_uvm

many thanks for your help!!!

create repo https://github.com/gengchaogit/blackwell-xid-wpr2-gsp-crash-recovery to automate this thing,thanks!

**Comment by bananenbaer** [comment]
Adding a data point from another game/config — Resident Evil Village (RE Engine, Steam appid 1196590) on Kubuntu 24.04.

**Hardware/software:**
- GPU: RTX 5060 Ti 16GB (GB206, PCI 10de:2d04)
- Driver: reproduces identically on both 580.95.05 and 580.159.03 (open kernel modules)
- Kernel: reproduces on both 6.17.0-40-generic and 7.0.0-28-generic
- Ubuntu 24.04.4 LTS, KDE Plasma, X11 session
- CPU: AMD Ryzen (Raphael APU), NVIDIA GPU drives the display

**Reproduction:** 100% reproducible, always at the same point — the game plays its first cutscene fine, then hangs (black screen, frozen) at the start of the second cutscene immediately following it. Happens on a fresh boot, first launch, every time.

Tested across Steam, using:
- Proton Hotfix (stock, probably ~11.0) — hangs even earlier, first cutscene never plays
- GE-Proton 11-1, stock DXVK — 1st cutscene OK, hangs on 2nd
- GE-Proton 11-1 with `PROTON_USE_WINED3D=1` — changes the visual symptom (menu background videos render black/glitched, 2nd cutscene renders only in a small corner of the screen and glitched) then crashes when trying to skip video
- Disabling NVDEC hardware video decode via `GST_PLUGIN_FEATURE_RANK="nvh264dec:0,nvh265dec:0,nvdec:0,nvav1dec:0" %command%` — no effect, same hang
- `PROTON_NO_ESYNC=1 PROTON_NO_FSYNC=1 %command%` — no effect, same hang
- GPU clocks pinned via `nvidia-smi -lgc 2400,2400` (+ `-pm 1`) to rule out P-state transitions racing the context switch — no effect, same hang
- In-game HDR and DLSS/FSR already disabled — not a factor

Given it reproduces identically regardless of rendering backend (DXVK/Vulkan vs WineD3D/OpenGL), driver point-release, kernel version, and with hardware video decode explicitly disabled, this points at the same GSP-level context switch failure described in this issue rather than anything specific to video decode or a particular Proton build.

**dmesg (representative, repeats identically across many separate attempts):**
```NVRM: GPU at PCI:0000:01:00: GPU-d0275ddc-84ee-5773-b0ef-417cac393ac7
NVRM: Xid (PCI:0000:01:00): 109, pid=10104, name=re8.exe, channel 0x00000032, errorString CTX SWITCH TIMEOUT, Info 0x19c054 (**or 0x1c058, or 0x1c03c, or 0x19c03c**, seems random to me)
```
Happy to provide full dmesg/journalctl output, nvidia-bug-report.sh, or test further configs if it's useful for narrowing this down.

**Comment by qwertoyo** [comment]
**Additional data point: driver version correlates with Xid 109 frequency, not presence, on RTX 5070 Ti (GB203)**

Confirming this reproduces across the full driver range we've tested, with a clear frequency gradient rather than a fix at any version:

- **595.71.05 / 590.48.01**: Xid 109 CTX SWITCH TIMEOUT reliably within minutes, DX12 titles (confirmed: The Witcher 3 next-gen, `bin/x64_dx12/`)
- **610.43.02**: identical failure mode, same timescale — no improvement despite the newer branch (also reported by jfernandez in #1097 on the same title)
- **580.159.03**: same underlying crash still occurs, but frequency drops from minutes to hours. This matches the pattern in this thread (aligningmyself, 2026-05-20) reporting 580 as a workaround for Elden Ring — it is not a fix, just a lower hazard rate.

This is consistent with Loong0x00's root-cause analysis above: the GSP firmware halt behavior itself appears version-independent, and driver version is only shifting *how often* the triggering condition is hit, not eliminating it.

Still running the DX12 path day-to-day (ray tracing matters more than avoiding the occasional hours-scale freeze) on 580.159.03 — reboot is the recovery path when it happens.

Tracked internally as NVIDIA case 5990600.


----
disclaimer: post written by Claude, reviewed by myself

**Comment by farmerdingle** [comment]
Xid 109 (CTX SWITCH TIMEOUT) — RTX 5060 Ti, open kernel module, Deadlock via Proton
Summary

Random GPU hangs while playing Deadlock (Source 2 engine via Proton). Display freezes on the last rendered frame, audio loops on the last buffer, and the game process itself remains alive (must be force-closed). journalctl confirms Xid 109, CTX SWITCH TIMEOUT at the moment of each hang. This matches other open reports of Xid 109 on Blackwell hardware under Linux (e.g. issue #1097 on this repo, RTX 5090 + Crimson Desert).

System
GPU: ZOTAC GAMING GeForce RTX 5060 Ti Twin Edge OC, 8GB GDDR7
Power connector: Single 8-pin PCIe (not 12VHPWR) — reseated, confirmed fully connected
CPU: AMD Ryzen 5 7600 (AM5, 6C/12T)
Motherboard: ASRock B650M PG Lightning WiFi 6E
RAM: Corsair Vengeance DDR5 16GB (2×8GB) 6000 MT/s CL36 — EXPO disabled, running JEDEC default; crash still reproduces, ruling out memory instability
PSU: ASRock PRO-750G, 750W, 80+ Gold, ATX 3.1
OS: Bazzite (bazzite-nvidia-open:stable), image version 44.20260802
NVRM/driver version: 610.43.03 (open kernel module, GSP firmware)
Kernel: 7.1.3-ogc5.1.fc44.x86_64 (Fedora Atomic base)
Display: Wayland (KDE Plasma, kwin_wayland)
Reproduction
Launch Deadlock via Steam/Proton on Bazzite
Play a normal match
At an unpredictable point (observed at both ~12 min and ~20 min into separate sessions), the display freezes on the current frame while in-game audio loops on the last played sound effect
Game process remains running (confirmed via ps/task manager) and must be manually killed
No consistent trigger identified (not tied to a specific in-game action, area, or asset load)
Log evidence
NVRM: Xid (PCI:0000:01:00): 109, pid=7741, name=MainThrd, channel 0x0000000a, errorString CTX SWITCH TIMEOUT, Info 0xc00c
NVRM: Xid (PCI:0000:01:00): 109, pid=10885, name=MainThrd, channel 0x0000000e, errorString CTX SWITCH TIMEOUT, Info 0x9c014

Recurred after mitigation attempts (GE-Proton + 170W power limit):

NVRM: Xid (PCI:0000:01:00): 109, pid=5626, name=MainThrd, channel 0x00000007, errorString CTX SWITCH TIMEOUT, Info 0xc00a
Troubleshooting already performed
 Disabled EXPO / reverted RAM to JEDEC default — no change
 Confirmed on latest available Bazzite image (rpm-ostree status shows no update pending)
 Confirmed correct image variant for Blackwell (bazzite-nvidia-open, open kernel module)
 Confirmed 8-pin GPU power connector fully seated (this card does not use 12VHPWR)
 Ruled out thermal cause — no signs of throttling, temps normal per nvidia-smi during play
 Switched to GE-Proton (latest) — crash still occurs, same Xid 109 signature
 Reduced GPU power limit to 170W via LACT (stock cap is 180W) — crash still occurs; delayed onset in one session (~12-15 min stable vs. faster hangs previously) but not resolved. Combined with GE-Proton switch, so not isolated individually.
 Confirmed true/exclusive fullscreen (not borderless) in-game — did not prevent recurrence
 Not yet tested: proprietary (non-open) driver — Blackwell is expected to require the open kernel module on Linux, but not independently confirmed
 Not yet tested: power limit below 150W
 Not yet tested: overlays fully disabled (Steam/Discord)

Conclusion so far: Neither reducing GPU power limit nor switching Proton runtime resolves the issue. Both were tested together in the same session, and the hang still occurred with an identical Xid 109 / CTX SWITCH TIMEOUT signature (see updated log below). This strongly suggests a driver-level fault rather than a configuration, power delivery, or compatibility-layer issue.

Notes

This appears consistent with other Xid 109 reports on Blackwell GPUs (RTX 5090, RTX 5060 Ti) across a range of driver branches, suggesting a systemic issue with GPU context switching under the open kernel module rather than a configuration or hardware fault specific to this system.

[nvidia-bug-report.log.gz](https://github.com/user-attachments/files/30862749/nvidia-bug-report.log.gz)

**Comment by killghar-hub** [comment]
GPU crash during gameplay: Xid 13 (UCODE Fatal Error) → GSP heartbeat timeout → full system lockup
System
Laptop: Acer Predator Helios Neo 16S AI (model PHN16S-71)
CPU: Intel Meteor Lake (Core Ultra series)
GPU: NVIDIA GeForce RTX 5070 Laptop (Blackwell)
BIOS: 1.26
OS: Bazzite (bazzite-nvidia-open), version 44.20260802, Fedora 44 base
Desktop: KDE Plasma 6, Wayland session (plasmashell / kwin_wayland)
NVIDIA driver: 610.43.03, open kernel modules (nvidia-open)
Symptom

Mid-game, the system freezes completely (black screen), requiring a hard power-button reboot to recover. No response to keyboard/mouse input once it starts.

Relevant log excerpt
NVRM: Xid (PCI:0000:01:00): 13, Graphics FECS Exception: UCODE Fatal Error
NVRM: Xid (PCI:0000:01:00): 13, pid=19820, name=OmenDemo.exe, channel 0x00000009
NVRM: GPU0 _kgspProcessRpcEvent: Failed to process received event 0x1004 (RC_TRIGGERED) from GPU0: status=0x57
[... repeats across multiple channels, including kwin_wayland ...]
NVRM: Xid (PCI:0000:01:00): 154, GPU recovery action changed from 0x0 (None) to 0x1 (PF FLR)
NVRM: Xid (PCI:0000:01:00): 38, pid=3081, name=plasmashell, channel 0x00000020
NVRM: Xid (PCI:0000:01:00): 109, pid=3081, name=plasmashell, channel 0x00000020, errorString CTX SWITCH TIMEOUT, Info 0x2f4027
[... repeats every few seconds for ~40 seconds ...]
NVRM: GPU0 _kgspIsHeartbeatTimedOut: Heartbeat timed out, currentTimeMs 158411200 heartbeat 3461532 heartbeatWithOffsetMs 158381197 diff 30003 timeout 5200
NVRM: GPU0 _kgspRpcRecvPoll: GSP RM heartbeat timed out
systemd: plasma-plasmashell.service: Failed with result 'core-dump'.
Sequence of events
Game process (OmenDemo.exe, running under Proton) triggers an Xid 13 Graphics FECS Exception — a fatal error inside the GPU's onboard microcode.
Driver attempts GPU recovery via PF FLR (function-level reset).
Recovery fails to fully restore the desktop compositor's GPU context — plasmashell starts hitting repeated Xid 109 CTX SWITCH TIMEOUT errors for ~40 seconds.
The GPU's onboard GSP (GPU System Processor) coprocessor stops responding entirely — heartbeat times out.
Full system lockup; only a hard reboot recovers it.
What I've already ruled out
Not thermal. CPU/GPU temps were well within normal range before and during the session (checked via sensors in prior troubleshooting on this same system).
Not the RTD3 power-cycling issue I'd previously fixed with NVreg_DynamicPowerManagement=0x01 — that was a separate bug causing lockscreen crashes during idle, unrelated to this.
NVreg_EnableGpuFirmware=0 (the standard GSP-disable workaround) does not apply here — it's unsupported on the nvidia-open driver, and GSP is mandatory on Blackwell GPUs regardless of driver branch.
Notes for the community

This looks consistent with other open reports of Xid 13/79/109 + GSP heartbeat timeouts on RTX 50-series (Blackwell) laptop GPUs under Linux, across driver versions in the 590–610 range. If anyone has found a working mitigation (driver version pin, kernel parameter, power limit, etc.) I'd appreciate hearing about it. Happy to provide full journalctl output or nvidia-bug-report.sh output on request.

**Comment by danilw** [comment]
> If anyone has found a working mitigation

@killghar-hub idk why it not mentioned here - there is workaround - [reddit link](https://www.reddit.com/r/linux_gaming/comments/1uzg3g5/warhammer_40000_space_marine_2_running_on_proton/)

you need to use https://github.com/HansKristian-Work/pyroveil and block `VK_NV_raw_access_chains` extension - on reddit link full instruction

**Comment by mabster** [comment]
**Data point: RTX 5070 (GB205), Hyprland/Wayland, Xid 8 + RC watchdog — recovered this time, no reboot**

System: RTX 5070 (GB205), nvidia-open **610.57.04**, kernel 7.1.9-arch1-2 (Arch/Omarchy), Hyprland 0.56.2 (Wayland compositor), Steam.

The only kernel log for the event:

```
NVRM: krcWatchdog_IMPL: RC watchdog: GPU is probably locked!  Notify Timeout Seconds: 7
NVRM: GPU at PCI:0000:02:00: GPU-208069ff-725f-0fae-3ebe-2b961b83c2e4
NVRM: Xid (PCI:0000:02:00): 8, pid=1440, name=Hyprland, channel 0x00000002
```

Context: ~35s after exiting Isle of Arrows (Steam app 1946970) on a desktop that had been continuously up for 4 days. Single Xid 8 — no Xid 109/154 cascade, no GSP heartbeat timeout logged; the RC watchdog was the first and only signal. (Note: an earlier near-identical event on this machine, also right after a different game's exit, is the reason this is worth reporting — it's not game-specific.)

Outcome (the point of my report): **the driver recovered on the same boot, no reboot required.** The hang triggered a GL context reset; Hyprland detected it via `glGetGraphicsResetStatus()` and asserted out (src/render/OpenGL.cpp:729), systemd restarted the compositor, and the session was back ~1 min later. `xdg-desktop-portal-hyprland` segfaulted at the same moment as a bystander.

For contrast: the earlier, near-identical hang on this machine (also post-game, also no suspend) produced the same failure family but the display froze and required a hard reset — so even when the driver sees the hang, whether recovery actually happens seems inconsistent (consistent with the missing Blackwell reset-recovery path described here).

Happy to answer follow-ups or supply a fresh `nvidia-bug-report.log` if my report is representative.
