### ISSUE TITLE
CUDA initialization failiure on latest release drivers

### ISSUE THREAD

**Issue by E-Allie** [NVIDIA/open-gpu-kernel-modules#797]
### NVIDIA Open GPU Kernel Modules Version

570.86.16 Release

### Please confirm this issue does not happen with the proprietary driver (of the same version). This issue tracker is only for bugs specific to the open kernel driver.

- [x] I confirm that this does not happen with the proprietary driver package.

### Operating System and Version

NixOS 25.05 (Warbler)

### Kernel Release

Linux 6.13.4 #1-NixOS SMP PREEMPT_DYNAMIC Fri Feb 21 13:11:21 UTC 2025 x86_64 GNU/Linux

### Please confirm you are running a stable release kernel (e.g. not a -rc). We do not accept bug reports for unreleased kernels.

- [x] I am running on a stable kernel release.

### Hardware: GPU

NVIDIA GeForce RTX 3080 Laptop GPU

### Describe the bug

The specific issue seems to have first been described here: https://github.com/NVIDIA/open-gpu-kernel-modules/discussions/780

When attempting to initialize NVDEC/CUDA in any capacity:

`cu->cuInit(0) failed -> CUDA_ERROR_NOT_INITIALIZED: initialization`

is returned.

This does not occur on proprietary kernel.

Setting "uvm_disable_hmm=1" on open kernel, as described in the above link, also worksaround/solves the issue.

### To Reproduce

This occurred when using any program trying to use CUDA/NVDEC.

I ran into it while using:

`ffmpeg -y -vsync 0 -hwaccel cuda -hwaccel_output_format cuda -i input.mp4 -c:a copy -c:v h264_nvenc -b:v 5M output.mp4`

which would return

`[AVHWDeviceContext @ 0x359865c0] cu->cuInit(0) failed -> CUDA_ERROR_NOT_INITIALIZED: initialization error`.

Similar initialization error would occur when invoking "vainfo" [through nvidia-vaapi-driver]

### Bug Incidence

Always

### nvidia-bug-report.log.gz

Will generate shortly after initial posting:

**Comment by E-Allie** [comment]
After reading over all 3 generated bug reports, it seems that

`/sys/module/nvidia_uvm/parameters/uvm_disable_hmm:N` is constant, which is decidedly odd as I'm definitely setting it to 1/Y in modprobe under success

The key difference is that the addressing mode reported in nvidia-smi is HMM when failing, and None when working

**Comment by Diatrus** [comment]
I can also corroborate this issue on Debian, Intel i5-12600KF + RTX 4070

**Comment by E-Allie** [comment]
Different issue I've been encountering that seems to be root caused by this:

For a while I could not use DLSS through Proton, and just assumed it was a limitation of whatever games I was attempting to play etc etc, and had very non-descript error messages most of the time except "Crash on Streamline initialization"

The uvm-disable workaround outlined here also seems to have resolved "Cannot properly initialize DLSS" type issues

**Comment by E-Allie** [comment]
Still identically failing on 570.133.07

**Comment by E-Allie** [comment]
Update: Still identically failing on 575.52.01

**Comment by Diatrus** [comment]
Continuing to fail on latest drivers, issue seems to be getting more widespread.

**Comment by masterofobzene** [comment]
Noob here. Sorry. 
How do I apply the "uvm_disable_hmm:N" workaround?

**Comment by superbonaci** [comment]
I was getting this error too in Arch linux but fixed it:

```
[h264_nvenc @ 0x7d7270201ac0] dl_fn->cuda_dl->cuInit(0) failed -> CUDA_ERROR_NOT_INITIALIZED: initialization error
```

### Summary

`CUDA_ERROR_NOT_INITIALIZED` when any NVENC/NVDEC app starts on 575.64.05 *closed* modules. 100 % reproducible and 100 % fixed by disabling HMM.

| Item | Value |
|------|-------|
| GPU | RTX 4 series |
| Kernel | 6.12.40-lts |
| Driver | 575.64.05 (closed) |
| CUDA | 12.9 |
| Firmware | linux-firmware-nvidia 20250708-1 (GSP 575.64.05) |

### Reproducer

```
ffmpeg -f lavfi -i testsrc2 -c:v h264_nvenc -t 1 -y out.mp4
```

### Workaround

```
echo "options nvidia_uvm uvm_disable_hmm=1" | sudo tee /etc/modprobe.d/nvidia-uvm.conf
sudo mkinitcpio -P
sudo depmod -a
sudo reboot
```

After reboot should show "Y" or "1":

```
sudo systool -vm nvidia_uvm | grep uvm_disable_hmm
```

if needed reinstall:

```
sudo pacman -Syu linux-firmware-nvidia
sudo pacman -Qk linux-firmware-nvidia | grep 'altered size' && sudo pacman -S linux-firmware-nvidia --overwrite '*'
sudo mkinitcpio -P
sudo reboot
```

this should return nothing:

```
sudo find /lib/modules/$(uname -r)/updates/dkms -name 'nvidia*.ko*'
lsmod | grep nova_core
```

**Comment by vishal14051992** [comment]
Hello All,

Hope you are doing good.
I encountered this problem on a customer's setup with SuperMicro [AS -2025HS-TNR] + Nvidia L40s GPU.

Reproducer,

Created torch venv using pip.

~~~
[root@localhost roothome]# source torch/bin/activate

(torch) [root@localhost roothome]# python
Python 3.9.18 (main, Dec  4 2024, 00:00:00) 
[GCC 11.4.1 20231218 (Red Hat 11.4.1-3)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.version.cuda)
12.8
>>> print(torch.__version__)
2.8.0+cu128
>>> print(torch.cuda.is_available())
/var/roothome/torch/lib64/python3.9/site-packages/torch/cuda/__init__.py:182: UserWarning: CUDA initialization: CUDA driver initialization failed, you might not have a CUDA gpu. (Triggered internally at /pytorch/c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
False
~~~

But after applying the workaround of nvidia_uvm, it worked.

~~~
# modprobe nvidia_uvm uvm_disable_hmm=1
~~~

After checking some upstream commit, I tried following 2 commits.

7ffb791423c7 ("x86/kaslr: Reduce KASLR entropy on most x86 systems")
7170130e4c72 ("x86/mm/init: Handle the special case of device private pages in add_pages(), to not increase max_pfn and trigger dma_addressing_limited() bounce buffers")

I created test custom kernel with these 2 patches and tested on same system with reproducer
and now CUDA works without the nvidia_uvm workaround.

**Comment by vishal14051992** [comment]
Hello All,

Just additional info.

For reference, I got following logs when I enabled debug on nvidia and nvidia_uvm modules

~~~
# modprobe nvidia NVreg_ResmanDebugLevel=0
modprobe nvidia NVreg_ResmanDebugLevel=0

# modprobe nvidia_uvm uvm_debug_prints=1
modprobe nvidia_uvm uvm_debug_prints=1
~~~

I got following error.

~~~
<4>[ 1062.336158] NVRM: VM: nv_alloc_pages:3801: 0x0000000021ac81f7, 32 page(s), count = 1, flags = 0x00000004, page_table = 0x00000000677eb7bb
<3>[ 1062.339224] nvidia-uvm: uvm_pmm_gpu.c:3480 devmem_init[pid:6006] request_free_mem_region() err -34
<3>[ 1062.339530] nvidia-uvm: uvm_gpu.c:1311 init_gpu[pid:6006] PMM initialization failed: Failure: Generic Error [NV_ERR_GENERIC], GPU ID 1: GPU-de9f6996-a0bf-2443-d0b7-eca4d994dab2 UVM-GI-de9f6996-a0bf-2443-d0b7-eca4d994dab2
~~~

Here the function `request_free_mem_region` is part of kernel source code and above 2 patches has to do with this function.

**Comment by Diatrus** [comment]
Also attempted using `nokaslr` as a workaround, but issue still occurs on kernel 6.14.11 unless I disable hmm.

**Comment by plopresti** [comment]
I encountered this issue as well (#947). Thank you @Diatrus for the pointer to the uvm_disable_hmm work-around.

I have some questions.

1. Is this a bug in the open GPU kernel module? If not, why is the proprietary module unaffected?
2. If so, is the bug understood? Will it be fixed? When?
3. Are there any functional or performance downsides of disabling HMM?
4. I encountered this issue only on my AMD-based L20 servers. My Intel-based A100 and L40S servers are unaffected. (I confirmed this across multiple Linux kernel and open driver versions.) Is this expected?

Thank you.

**Comment by Diatrus** [comment]
@superbonaci this has not yet been acknowledged by Nvidia, so I don’t have an answer to most of these questions. Performance/functional downsides are the fact that you will no longer have unified memory support, severely constraining video memory if you expect programs to also dip into the system memory. I can also tell you this has persisted on Intel kernel versions 6.8-6.14 for me.

**Comment by plopresti** [comment]
@Diatrus Thanks. I intended my questions for NVIDIA. Hopefully someone there will take up this bug report eventually.

It is possible that the issue is related to A100/L40S vs L20 and not Intel vs. AMD. Or perhaps something else. It is definitely configuration dependent, which could explain why this issue is not receiving more attention.

**Comment by superbonaci** [comment]
So just a question, HMM is enabled and working by default in Windows 11? This is just a Linux issue right now is that correct? I don't ask about FreeBSD because not tested.

**Comment by E-Allie** [comment]
> So just a question, HMM is enabled and working by default in Windows 11? This is just a Linux issue right now is that correct? I don't ask about FreeBSD because not tested.

Yes, this seems to be the case.

Specifically, the issue only occurs on the Open Kernel Modules, and not the fully proprietary stack. On Windows [assuming you don't mean WSL], the proprietary stack is the only option right now.

**Comment by Diatrus** [comment]
Confirmed issue persists with 580.95.05 on kernel 6.17.1.

**Comment by vishal14051992** [comment]
@Diatrus can you share debug logs of nvidia module and nvidia_uvm module?

**Comment by Qubitium** [comment]
Nvidia, please fix this! I wasted 4+ hours fixing this only to find this github issue.. Thank god I found it. All thanks to @E-Allie and gang for finding the source cause. Nvidia needs to fix the actual bug now.   

580.95.05 ubuntu 24.04. Tried 6.8, 6.11, 6.14 kernels and all had the same issue. After hitting the bug, rolling back to older 570 and 575 drivers was also broken1 It appears the uvm settings is persistent after you install/init/load the latest broken drivers.

**Comment by wenjianhn** [comment]
@Qubitium cloud you please verify if the latest kernel of Ubuntu has fixed the issue?
See [x86 systems with PCIe BAR addresses located outside a certain range see P2PDMA allocation failures and CUDA initialization errors](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/2120209)

**Comment by wenjianhn** [comment]
We have verified that the latest kernel (6.8.0-88-generic) of Ubuntu has fixed the issue.

**Comment by superbonaci** [comment]
It doesn't seem to happen anymore on kernel `Linux arch 6.12.60-1-lts`.

**Comment by plopresti** [comment]
> After checking some upstream commit, I tried following 2 commits.
> 
> 7ffb791423c7 ("x86/kaslr: Reduce KASLR entropy on most x86 systems") 7170130e4c72 ("x86/mm/init: Handle the special case of device private pages in add_pages(), to not increase max_pfn and trigger dma_addressing_limited() bounce buffers")
> 
> I created test custom kernel with these 2 patches and tested on same system with reproducer and now CUDA works without the nvidia_uvm workaround.

Thanks @vishal14051992. Red Hat has been tracking this as RHEL-129452, I think. That is the reference that shows up in the ChangeLog for kernel-6.12.0-124.31.1, which incorporates these fixes for EL10.

**Comment by E-Allie** [comment]
Closing this issue unless others still have the same problems, it seems to have been fixed upstream in the mainline kernel [fixed on 6.19.6 for me]

**Comment by jcelerier** [comment]
@E-Allie I'm on 6.19.6 and still have the problem

```
$ nvidia-smi
Tue Mar 17 16:49:26 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 590.48.01              Driver Version: 590.48.01      CUDA Version: 13.1     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3060 ...    On  |   00000000:01:00.0 Off |                  N/A |
| N/A   49C    P8             12W /   80W |       1MiB /   6144MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
```

**Comment by jcelerier** [comment]
Update to 6.19.7 and driver 595 and it works again, but I don't know what could be the cause or if it was just a transient error

**Comment by edmcman** [comment]
I am having this issue on 580.159.03 on 6.8.0-111-generic #111~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC. NVIDIA GeForce RTX 4070. Proprietary driver works fine.
