### ISSUE TITLE
kgspBootstrap_GH100: GSP-FMC reported an error while attempting to boot GSP

### ISSUE THREAD

**Issue by Cyrille37** [NVIDIA/open-gpu-kernel-modules#974]
### NVIDIA Open GPU Kernel Modules Version

nvidia-headless-580-open

### Please confirm this issue does not happen with the proprietary driver (of the same version). This issue tracker is only for bugs specific to the open kernel driver.

- [x] I confirm that this does not happen with the proprietary driver package.

### Operating System and Version

Ubuntu 24.04.3 LTS

### Kernel Release

Linux NS5x-NS7xAU 6.14.0-36-generic #36~24.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Oct 15 15:45:17 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Please confirm you are running a stable release kernel (e.g. not a -rc). We do not accept bug reports for unreleased kernels.

- [x] I am running on a stable kernel release.

### Hardware: GPU

PNY OC 16G Geforce RTX 5060 Ti

### Describe the bug

preamble: I use the PCI brige "Cyid TB3-HL7" connected with a Thunderbolt 4 cable. It works fine with a Gigabyte Windforce OC 12G GForce RTX 3060 with driver `nvidia-headless-580-open nvidia-dkms-580-open`.

I've just buy a PNY OC 16GB Geforce RTX 5060 Ti to replace the previous, but it does not work as you will see in nvidia-bug-report.log.gz

### To Reproduce

- power on the laptop
- plug the 5060 on the PCI Bridge (_Cyid TB3-HL7_)
- plug power wire to 5060
- plug power wire to PCI Bridge
- plug the Thunderbolt 4 wire on the bridge then the laptop
then
- `nvidia-msi` does not find the card
- many error in the system journal

### Bug Incidence

Always

### nvidia-bug-report.log.gz

[nvidia-bug-report.log.gz](https://github.com/user-attachments/files/23757661/nvidia-bug-report.log.gz)

### More Info

Installed packages : 
```
$ dpkg --get-selections | grep -i nvidia
libnvidia-cfg1-580:amd64			install
libnvidia-common-580				install
libnvidia-compute-535:amd64			deinstall
libnvidia-compute-580:amd64			install
libnvidia-decode-580:amd64			install
libnvidia-gpucomp-580:amd64			install
libnvidia-ml-dev:amd64				install
nvidia-cuda-dev:amd64				install
nvidia-dkms-580-open				install
nvidia-driver-assistant				install
nvidia-firmware-580				install
nvidia-headless-580-open			install
nvidia-headless-no-dkms-580-open		install
nvidia-kernel-common-580			install
nvidia-kernel-source-580-open			install
nvidia-modprobe					install
nvidia-persistenced				install
nvidia-utils-580				install
```

Here are some strange lines _which I don't understand_ : 
```
kernel: pci 0000:03:00.0: bridge window [mem size 0x24400000 64bit pref]: can't assign; no space
...
kernel: pci 0000:03:00.0: bridge window [io  size 0x3000]: can't assign; no space
```

I've identified this error lines :
```
kernel: [drm] [nvidia-drm] [GPU ID 0x00000500] Loading driver
kernel: NVRM: GPU at PCI:0000:05:00: GPU-ab296f23-e6a6-a23b-b6c1-33f9b813df84
kernel: NVRM: Xid (PCI:0000:05:00): 79, GPU has fallen off the bus.
kernel: NVRM: GPU 0000:05:00.0: GPU has fallen off the bus.
kernel: NVRM: kgspRcAndNotifyAllChannels_IMPL: RC all channels for critical error 79.
...
kgspBootstrap_GH100: GSP-FMC reported an error while attempting to boot GSP: 0xffffffff
_kgspBootGspRm: unexpected WPR2 already up, cannot proceed with booting GSP
_kgspBootGspRm: (the GPU is likely in a bad state and may need to be reset)
RmInitAdapter: Cannot initialize GSP firmware RM
...
```

**Comment by Deadshot0x7** [comment]
@mtijanic  @mmaneetsingh  ,  Can anyone from you assign me this issue to me as I'm really Interested to solve this issue

**Comment by Cyrille37** [comment]
Hi @Deadshot0x7 
Just as a reminder : I did some tests with RTX 5060 Ti plugged with a PCI/THB4 Bridge (eGPU).

With 2 products:
- "Cyid TB3-HL7" that never work
- "Wikingoo L17" that works but fails easily on AI inference

I will looking forward :-)
Regards & Cheers

**Comment by mtijanic** [comment]
> [@mtijanic](https://github.com/mtijanic) [@mmaneetsingh](https://github.com/mmaneetsingh) , Can anyone from you assign me this issue to me as I'm really Interested to solve this issue

Sorry @Deadshot0x7 , but most of these issues you are requesting assignment on likely are not actually solvable by an external contributor as they involve the interface between firmware and CPU, and changes to the firmware can only be done by NVIDIA.
Additionally, we will not assign issues to external contributors as that can lead to unreasonable expectations. If you do manage to solve a bug - particularly an untriaged one - feel free to open a PR directly.


@Cyrille37 sorry, still no update here, but I've updated the issue title to better reflect the problem at hand, hopefully that makes it easier to triage. _Maybe_ running with [RmMsg=':'](https://github.com/NVIDIA/open-gpu-kernel-modules/discussions/197) might provide more insight.

**Comment by azmeuk** [comment]
I can document a similar issue for me. I run a [AORUS RTX 5060 Ti AI BOX](https://www.gigabyte.com/fr/Graphics-Card/GV-N506TIXEB-16GD) connected on a Thunderbolt 4 port on a [Framework Laptop 13 (Intel Core Ultra Series 1 / Meteor Lake) ](https://frame.work/en/en/laptop13). I use the original Thunderbolt cable and PSU that came in the GPU box.

I run kernel 6.18.13-arch1-1 on Archlinux with nvidia-open 590.48.01 and a GNOME session.

The GPU is detected correctly and `nvidia-smi` works at idle. However, any CUDA initialization crashes the GPU immediately with Xid 79 ("GPU has fallen off the bus"), followed by the xHCI host controller dying and all USB devices disconnecting.

Even the most minimal CUDA call reproduces the crash:

```console
$ python3 -c "import torch; print(torch.cuda.is_available()); t = torch.zeros(1).cuda(); print(t)"
```

GNOME does not use the eGPU for rendering (switcherooctl confirms only the Intel iGPU is used for display).

I have tried several things but none helped:

  - GRUB boot options `pcie_ports=native pcie_aspm=off pci=assign-busses,realloc,hpmmiosize=128M,hpmmioprefsize=16G`
  - Early loading modules in initramfs: MODULES=(thunderbolt nvidia nvidia_modeset nvidia_uvm nvidia_drm)
  - nvidia-smi -pm 1 (persistence mode) — crash becomes even more immediate
  - NVreg_DynamicPowerManagement=0x00

Some related logs:

<details>
<summary>  lspci -k -d ::03xx</summary>

```
  00:02.0 VGA compatible controller: Intel Corporation Meteor Lake-P [Intel Graphics] (rev 08)                               
      Subsystem: Framework Computer Inc. Device 0009                                                                         
      Kernel driver in use: i915                                                                                             
      Kernel modules: i915, xe                                                                                               
  2d:00.0 VGA compatible controller: NVIDIA Corporation GB206 [GeForce RTX 5060 Ti] (rev a1)                                 
      Subsystem: Gigabyte Technology Co., Ltd Device 41cd                                                                    
      Kernel driver in use: nvidia                                                                                           
      Kernel modules: nouveau, nvidia_drm, nvidia  
```
</details>

<details>
<summary>nvidia-smi</summary>

```
  +-----------------------------------------------------------------------------------------+                                
  | Processes:                                                                              |                                
  |  GPU   GI   CI              PID   Type   Process name                        GPU Memory |                                
  |        ID   ID                                                               Usage      |                                
  |=========================================================================================|                                
  |    0   N/A  N/A            3803      G   /usr/bin/gnome-shell                      2MiB |                                
  +-----------------------------------------------------------------------------------------+                                
  Tue Mar  3 09:33:47 2026                                                                                                   
  +-----------------------------------------------------------------------------------------+                                
  | NVIDIA-SMI 590.48.01              Driver Version: 590.48.01      CUDA Version: 13.1     |                                
  +-----------------------------------------+------------------------+----------------------+                                
  | GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |                                
  | Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |                                
  |                                         |                        |               MIG M. |                                
  |=========================================+========================+======================|                                
  |   0  NVIDIA GeForce RTX 5060 Ti     Off |   00000000:2D:00.0 Off |                  N/A |                                
  |  0%   43C    P8              6W /  180W |      13MiB /  16311MiB |      0%      Default |                                
  |                                         |                        |                  N/A |                                
  +-----------------------------------------+------------------------+----------------------+                                
                                                                                                                             
  +-----------------------------------------------------------------------------------------+                                
  | Processes:                                                                              |                                
  |  GPU   GI   CI              PID   Type   Process name                        GPU Memory |                                
  |        ID   ID                                                               Usage      |                                
  |=========================================================================================|                                
  |    0   N/A  N/A            3803      G   /usr/bin/gnome-shell                      2MiB |                                
  +-----------------------------------------------------------------------------------------+   
```

</details>

<details>
<summary>dmesg</summary>

```
[  212.843620] NVRM: GPU at PCI:0000:2d:00: GPU-2f90989b-2e46-903b-bf4d-eac10494d5ae                      
  [  212.843651] NVRM: GPU Board Serial Number: 0                                                                            
  [  212.843653] NVRM: Xid (PCI:0000:2d:00): 79, GPU has fallen off the bus.                                                 
  [  212.843668] NVRM: GPU 0000:2d:00.0: GPU has fallen off the bus.                                                         
  [  212.843671] NVRM: GPU 0000:2d:00.0: GPU serial number is 0.                                                             
  [  212.843678] NVRM: krcRcAndNotifyAllChannels_IMPL: RC all channels for critical error 79.                                
  [  212.843697] NVRM: _threadNodeCheckTimeout: API_GPU_ATTACHED_SANITY_CHECK failed!                                        
  [  212.843707] NVRM: _threadNodeCheckTimeout: API_GPU_ATTACHED_SANITY_CHECK failed!                                        
  [  212.843712] NVRM: _threadNodeCheckTimeout: API_GPU_ATTACHED_SANITY_CHECK failed!                                        
  [  212.843718] NVRM: _threadNodeCheckTimeout: API_GPU_ATTACHED_SANITY_CHECK failed!                                        
  [  212.843723] NVRM: _threadNodeCheckTimeout: API_GPU_ATTACHED_SANITY_CHECK failed!                                        
  [  212.843726] NVRM: _threadNodeCheckTimeout: API_GPU_ATTACHED_SANITY_CHECK failed!                                        
  [  212.843729] NVRM: _threadNodeCheckTimeout: API_GPU_ATTACHED_SANITY_CHECK failed!                                        
  [  212.843733] NVRM: _threadNodeCheckTimeout: API_GPU_ATTACHED_SANITY_CHECK failed!                                        
  [  212.843736] NVRM: _threadNodeCheckTimeout: API_GPU_ATTACHED_SANITY_CHECK failed!                                        
  [  212.843740] NVRM: _threadNodeCheckTimeout: API_GPU_ATTACHED_SANITY_CHECK failed!                                        
  [  212.843743] NVRM: _threadNodeCheckTimeout: API_GPU_ATTACHED_SANITY_CHECK failed!                                        
  [  212.843749] NVRM: _threadNodeCheckTimeout: API_GPU_ATTACHED_SANITY_CHECK failed!                                        
  [  212.843755] NVRM: _threadNodeCheckTimeout: API_GPU_ATTACHED_SANITY_CHECK failed!                                        
  [  212.843761] NVRM: _threadNodeCheckTimeout: API_GPU_ATTACHED_SANITY_CHECK failed!                                        
  [  212.843770] NVRM: _threadNodeCheckTimeout: API_GPU_ATTACHED_SANITY_CHECK failed!                                        
  [  212.843772] NVRM: _threadNodeCheckTimeout: API_GPU_ATTACHED_SANITY_CHECK failed!                                        
  [  212.843776] NVRM: _threadNodeCheckTimeout: API_GPU_ATTACHED_SANITY_CHECK failed!                                        
  [  212.843781] NVRM: _threadNodeCheckTimeout: API_GPU_ATTACHED_SANITY_CHECK failed!                                        
  [  212.843784] NVRM: _threadNodeCheckTimeout: API_GPU_ATTACHED_SANITY_CHECK failed!                                        
  [  212.844090] NVRM: nvGpuOpsReportFatalError: uvm encountered global fatal error 0x60, requiring os reboot to recover.    
  [  212.893737] NVRM: prbEncStartAlloc: Can't allocate memory for protocol buffers.                                         
  [  212.893740] NVRM: A GPU crash dump has been created. If possible, please run                                            
                 NVRM: nvidia-bug-report.sh as root to collect this data before                                              
                 NVRM: the NVIDIA kernel module is unloaded.                                                                 
  [  212.994013] NVRM: Xid (PCI:0000:2d:00): 154, GPU recovery action changed from 0x0 (None) to 0x2 (Node Reboot Required)  
  [  212.994303] NVRM: GPU0 _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 10 sequence 3544!          
  [  212.994306] NVRM: GPU0 rpcRmApiFree_GSP: GspRmFree failed: hClient=0xc1d00001; hObject=0xcaf00113;                      
  paramsStatus=0x00000000; status=0x0000000f                                                                                 
  [  212.994308] NVRM: GPU0 nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status ==                           
  NV_ERR_GPU_IN_FULLCHIP_RESET) @ rs_client.c:844                                                                            
  [  212.994315] NVRM: nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status == NV_ERR_GPU_IN_FULLCHIP_RESET)  
  @ rs_server.c:259                                                                                                          
  [  212.994317] NVRM: nvAssertFailedNoLog: Assertion failed: status == NV_OK @ nv_gpu_ops.c:10457                           
  [  212.994323] NVRM: GPU0 _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 10 sequence 3545!          
  [  212.994324] NVRM: GPU0 rpcRmApiFree_GSP: GspRmFree failed: hClient=0xc1d00001; hObject=0xcaf00112;                      
  paramsStatus=0x00000000; status=0x0000000f                                                                                 
  [  212.994324] NVRM: GPU0 nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status ==                           
  NV_ERR_GPU_IN_FULLCHIP_RESET) @ rs_client.c:844                                                                            
  [  212.994327] NVRM: nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status == NV_ERR_GPU_IN_FULLCHIP_RESET)  
  @ rs_server.c:259                                                                                                          
  [  212.994328] NVRM: nvAssertFailedNoLog: Assertion failed: status == NV_OK @ nv_gpu_ops.c:10466                           
  [  212.994333] NVRM: GPU0 _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 10 sequence 3546!          
  [  212.994334] NVRM: GPU0 rpcRmApiFree_GSP: GspRmFree failed: hClient=0xc1d00001; hObject=0xcaf00110;                      
  paramsStatus=0x00000000; status=0x0000000f                                                                                 
  [  212.994335] NVRM: GPU0 nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status ==                           
  NV_ERR_GPU_IN_FULLCHIP_RESET) @ rs_client.c:844                                                                            
  [  212.994338] NVRM: nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status == NV_ERR_GPU_IN_FULLCHIP_RESET)  
  @ rs_server.c:259                                                                                                          
  [  212.994339] NVRM: nvAssertFailedNoLog: Assertion failed: status == NV_OK @ nv_gpu_ops.c:10472                           
  [  212.994340] NVRM: nvAssertFailedNoLog: Assertion failed: status == NV_OK @ nv_gpu_ops.c:10478                           
  [  212.994718] NVRM: _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 78 sequence 3547!               
  [  212.994722] NVRM: nvCheckOkFailedNoLog: Check failed: GPU lost from the bus [NV_ERR_GPU_IS_LOST] (0x0000000F) returned  
  from nvdEngineDumpCallbackHelper(pGpu, pPrbEnc, pNvDumpState, pEngineCallback) @ nv_debug_dump.c:273                       
  [  212.994745] NVRM: _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 78 sequence 3548!               
  [  212.994747] NVRM: nvCheckOkFailedNoLog: Check failed: GPU lost from the bus [NV_ERR_GPU_IS_LOST] (0x0000000F) returned  
  from nvdEngineDumpCallbackHelper(pGpu, pPrbEnc, pNvDumpState, pEngineCallback) @ nv_debug_dump.c:273                       
  [  212.994749] NVRM: _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 78 sequence 3549!               
  [  212.994750] NVRM: nvCheckOkFailedNoLog: Check failed: GPU lost from the bus [NV_ERR_GPU_IS_LOST] (0x0000000F) returned  
  from nvdEngineDumpCallbackHelper(pGpu, pPrbEnc, pNvDumpState, pEngineCallback) @ nv_debug_dump.c:273                       
  [  212.994752] NVRM: _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 78 sequence 3550!               
  [  212.994753] NVRM: nvCheckOkFailedNoLog: Check failed: GPU lost from the bus [NV_ERR_GPU_IS_LOST] (0x0000000F) returned  
  from nvdEngineDumpCallbackHelper(pGpu, pPrbEnc, pNvDumpState, pEngineCallback) @ nv_debug_dump.c:273                       
  [  212.994755] NVRM: _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 78 sequence 3551!               
  [  212.994756] NVRM: nvCheckOkFailedNoLog: Check failed: GPU lost from the bus [NV_ERR_GPU_IS_LOST] (0x0000000F) returned  
  from nvdEngineDumpCallbackHelper(pGpu, pPrbEnc, pNvDumpState, pEngineCallback) @ nv_debug_dump.c:273                       
  [  212.994759] NVRM: _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 78 sequence 3552!               
  [  212.994759] NVRM: nvCheckOkFailedNoLog: Check failed: GPU lost from the bus [NV_ERR_GPU_IS_LOST] (0x0000000F) returned  
  from nvdEngineDumpCallbackHelper(pGpu, pPrbEnc, pNvDumpState, pEngineCallback) @ nv_debug_dump.c:273                       
  [  212.994762] NVRM: _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 78 sequence 3553!               
  [  212.994763] NVRM: nvCheckOkFailedNoLog: Check failed: GPU lost from the bus [NV_ERR_GPU_IS_LOST] (0x0000000F) returned  
  from nvdEngineDumpCallbackHelper(pGpu, pPrbEnc, pNvDumpState, pEngineCallback) @ nv_debug_dump.c:273                       
  [  212.994765] NVRM: _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 78 sequence 3554!               
  [  212.994766] NVRM: nvCheckOkFailedNoLog: Check failed: GPU lost from the bus [NV_ERR_GPU_IS_LOST] (0x0000000F) returned  
  from nvdEngineDumpCallbackHelper(pGpu, pPrbEnc, pNvDumpState, pEngineCallback) @ nv_debug_dump.c:273                       
  [  212.994768] NVRM: _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 78 sequence 3555!               
  [  212.994769] NVRM: nvCheckOkFailedNoLog: Check failed: GPU lost from the bus [NV_ERR_GPU_IS_LOST] (0x0000000F) returned  
  from nvdEngineDumpCallbackHelper(pGpu, pPrbEnc, pNvDumpState, pEngineCallback) @ nv_debug_dump.c:273                       
  [  212.994771] NVRM: _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 78 sequence 3556!               
  [  212.994772] NVRM: nvCheckOkFailedNoLog: Check failed: GPU lost from the bus [NV_ERR_GPU_IS_LOST] (0x0000000F) returned  
  from nvdEngineDumpCallbackHelper(pGpu, pPrbEnc, pNvDumpState, pEngineCallback) @ nv_debug_dump.c:273                       
  [  212.994774] NVRM: _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 78 sequence 3557!               
  [  212.994775] NVRM: nvCheckOkFailedNoLog: Check failed: GPU lost from the bus [NV_ERR_GPU_IS_LOST] (0x0000000F) returned  
  from nvdEngineDumpCallbackHelper(pGpu, pPrbEnc, pNvDumpState, pEngineCallback) @ nv_debug_dump.c:273                       
  [  212.994777] NVRM: _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 78 sequence 3558!               
  [  212.994778] NVRM: nvCheckOkFailedNoLog: Check failed: GPU lost from the bus [NV_ERR_GPU_IS_LOST] (0x0000000F) returned  
  from nvdEngineDumpCallbackHelper(pGpu, pPrbEnc, pNvDumpState, pEngineCallback) @ nv_debug_dump.c:273                       
  [  212.994781] NVRM: _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 78 sequence 3559!               
  [  212.994781] NVRM: nvCheckOkFailedNoLog: Check failed: GPU lost from the bus [NV_ERR_GPU_IS_LOST] (0x0000000F) returned  
  from nvdEngineDumpCallbackHelper(pGpu, pPrbEnc, pNvDumpState, pEngineCallback) @ nv_debug_dump.c:273                       
  [  212.994784] NVRM: _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 78 sequence 3560!               
  [  212.994785] NVRM: nvCheckOkFailedNoLog: Check failed: GPU lost from the bus [NV_ERR_GPU_IS_LOST] (0x0000000F) returned  
  from nvdEngineDumpCallbackHelper(pGpu, pPrbEnc, pNvDumpState, pEngineCallback) @ nv_debug_dump.c:273                       
  [  212.994787] NVRM: _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 78 sequence 3561!               
  [  212.994788] NVRM: nvCheckOkFailedNoLog: Check failed: GPU lost from the bus [NV_ERR_GPU_IS_LOST] (0x0000000F) returned  
  from nvdEngineDumpCallbackHelper(pGpu, pPrbEnc, pNvDumpState, pEngineCallback) @ nv_debug_dump.c:273                       
  [  212.994790] NVRM: _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 78 sequence 3562!               
  [  212.994791] NVRM: nvCheckOkFailedNoLog: Check failed: GPU lost from the bus [NV_ERR_GPU_IS_LOST] (0x0000000F) returned  
  from nvdEngineDumpCallbackHelper(pGpu, pPrbEnc, pNvDumpState, pEngineCallback) @ nv_debug_dump.c:273                       
  [  212.994793] NVRM: _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 78 sequence 3563!               
  [  212.994794] NVRM: nvCheckOkFailedNoLog: Check failed: GPU lost from the bus [NV_ERR_GPU_IS_LOST] (0x0000000F) returned  
  from nvdEngineDumpCallbackHelper(pGpu, pPrbEnc, pNvDumpState, pEngineCallback) @ nv_debug_dump.c:273                       
  [  212.994796] NVRM: _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 78 sequence 3564!               
  [  212.994797] NVRM: nvCheckOkFailedNoLog: Check failed: GPU lost from the bus [NV_ERR_GPU_IS_LOST] (0x0000000F) returned  
  from nvdEngineDumpCallbackHelper(pGpu, pPrbEnc, pNvDumpState, pEngineCallback) @ nv_debug_dump.c:273                       
  [  212.994799] NVRM: _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 78 sequence 3565!               
  [  212.994800] NVRM: nvCheckOkFailedNoLog: Check failed: GPU lost from the bus [NV_ERR_GPU_IS_LOST] (0x0000000F) returned  
  from nvdEngineDumpCallbackHelper(pGpu, pPrbEnc, pNvDumpState, pEngineCallback) @ nv_debug_dump.c:273                       
  [  212.994803] NVRM: _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 78 sequence 3566!               
  [  212.994803] NVRM: nvCheckOkFailedNoLog: Check failed: GPU lost from the bus [NV_ERR_GPU_IS_LOST] (0x0000000F) returned  
  from nvdEngineDumpCallbackHelper(pGpu, pPrbEnc, pNvDumpState, pEngineCallback) @ nv_debug_dump.c:273                       
  [  212.994806] NVRM: _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 78 sequence 3567!               
  [  212.994806] NVRM: nvCheckOkFailedNoLog: Check failed: GPU lost from the bus [NV_ERR_GPU_IS_LOST] (0x0000000F) returned  
  from nvdEngineDumpCallbackHelper(pGpu, pPrbEnc, pNvDumpState, pEngineCallback) @ nv_debug_dump.c:273                       
  [  212.994809] NVRM: _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 78 sequence 3568!               
  [  212.994809] NVRM: nvCheckOkFailedNoLog: Check failed: GPU lost from the bus [NV_ERR_GPU_IS_LOST] (0x0000000F) returned  
  from nvdEngineDumpCallbackHelper(pGpu, pPrbEnc, pNvDumpState, pEngineCallback) @ nv_debug_dump.c:273                       
  [  212.994811] NVRM: _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 78 sequence 3569!               
  [  212.994812] NVRM: nvCheckOkFailedNoLog: Check failed: GPU lost from the bus [NV_ERR_GPU_IS_LOST] (0x0000000F) returned  
  from nvdEngineDumpCallbackHelper(pGpu, pPrbEnc, pNvDumpState, pEngineCallback) @ nv_debug_dump.c:273                       
  [  212.994814] NVRM: _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 78 sequence 3570!               
  [  212.994815] NVRM: nvCheckOkFailedNoLog: Check failed: GPU lost from the bus [NV_ERR_GPU_IS_LOST] (0x0000000F) returned  
  from nvdEngineDumpCallbackHelper(pGpu, pPrbEnc, pNvDumpState, pEngineCallback) @ nv_debug_dump.c:273                       
  [  212.994817] NVRM: _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 78 sequence 3571!               
  [  212.994818] NVRM: nvCheckOkFailedNoLog: Check failed: GPU lost from the bus [NV_ERR_GPU_IS_LOST] (0x0000000F) returned  
  from nvdEngineDumpCallbackHelper(pGpu, pPrbEnc, pNvDumpState, pEngineCallback) @ nv_debug_dump.c:273                       
  [  212.994831] NVRM: nvAssertFailedNoLog: Assertion failed: status == NV_OK @ journal.c:2240                               
  [  212.994986] NVRM: GPU0 _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 10 sequence 3572!          
  [  212.994988] NVRM: GPU0 rpcRmApiFree_GSP: GspRmFree failed: hClient=0xc1d00071; hObject=0x5c00001b;                      
  paramsStatus=0x00000000; status=0x0000000f                                                                                 
  [  212.994988] NVRM: GPU0 nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status ==                           
  NV_ERR_GPU_IN_FULLCHIP_RESET) @ rs_client.c:844                                                                            
  [  212.995000] NVRM: nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status == NV_ERR_GPU_IN_FULLCHIP_RESET)  
  @ rs_server.c:259                                                                                                          
  [  212.995012] NVRM: GPU0 _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 10 sequence 3573!          
  [  212.995012] NVRM: GPU0 rpcRmApiFree_GSP: GspRmFree failed: hClient=0xc1d00071; hObject=0x5c00001c;                      
  paramsStatus=0x00000000; status=0x0000000f                                                                                 
  [  212.995013] NVRM: GPU0 nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status ==                           
  NV_ERR_GPU_IN_FULLCHIP_RESET) @ rs_client.c:844                                                                            
  [  212.995016] NVRM: nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status == NV_ERR_GPU_IN_FULLCHIP_RESET)  
  @ rs_server.c:259                                                                                                          
  [  212.995051] NVRM: GPU0 _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 10 sequence 3574!          
  [  212.995052] NVRM: GPU0 rpcRmApiFree_GSP: GspRmFree failed: hClient=0xc1d00071; hObject=0x5c00001a;                      
  paramsStatus=0x00000000; status=0x0000000f                                                                                 
  [  212.995172] NVRM: GPU0 _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 10 sequence 3575!          
  [  212.995173] NVRM: GPU0 rpcRmApiFree_GSP: GspRmFree failed: hClient=0xc1d00071; hObject=0x5c000021;                      
  paramsStatus=0x00000000; status=0x0000000f                                                                                 
  [  212.995173] NVRM: GPU0 nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status ==                           
  NV_ERR_GPU_IN_FULLCHIP_RESET) @ rs_client.c:844                                                                            
  [  212.995176] NVRM: nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status == NV_ERR_GPU_IN_FULLCHIP_RESET)  
  @ rs_server.c:259                                                                                                          
  [  212.995184] NVRM: GPU0 _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 10 sequence 3576!          
  [  212.995185] NVRM: GPU0 rpcRmApiFree_GSP: GspRmFree failed: hClient=0xc1d00071; hObject=0x5c000020;                      
  paramsStatus=0x00000000; status=0x0000000f                                                                                 
  [  212.995229] NVRM: GPU0 _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 10 sequence 3577!          
  [  212.995230] NVRM: GPU0 rpcRmApiFree_GSP: GspRmFree failed: hClient=0xc1d00071; hObject=0x5c000024;                      
  paramsStatus=0x00000000; status=0x0000000f                                                                                 
  [  212.995231] NVRM: GPU0 nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status ==                           
  NV_ERR_GPU_IN_FULLCHIP_RESET) @ rs_client.c:844                                                                            
  [  212.995233] NVRM: nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status == NV_ERR_GPU_IN_FULLCHIP_RESET)  
  @ rs_server.c:259                                                                                                          
  [  212.995238] NVRM: GPU0 _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 10 sequence 3578!          
  [  212.995239] NVRM: GPU0 rpcRmApiFree_GSP: GspRmFree failed: hClient=0xc1d00071; hObject=0x5c000025;                      
  paramsStatus=0x00000000; status=0x0000000f                                                                                 
  [  212.995239] NVRM: GPU0 nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status ==                           
  NV_ERR_GPU_IN_FULLCHIP_RESET) @ rs_client.c:844                                                                            
  [  212.995241] NVRM: nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status == NV_ERR_GPU_IN_FULLCHIP_RESET)  
  @ rs_server.c:259                                                                                                          
  [  212.995247] NVRM: GPU0 _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 10 sequence 3579!          
  [  212.995248] NVRM: GPU0 rpcRmApiFree_GSP: GspRmFree failed: hClient=0xc1d00071; hObject=0x5c000023;                      
  paramsStatus=0x00000000; status=0x0000000f                                                                                 
  [  212.995286] NVRM: GPU0 _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 10 sequence 3580!          
  [  212.995287] NVRM: GPU0 rpcRmApiFree_GSP: GspRmFree failed: hClient=0xc1d00071; hObject=0x5c000028;                      
  paramsStatus=0x00000000; status=0x0000000f                                                                                 
  [  212.995287] NVRM: GPU0 nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status ==                           
  NV_ERR_GPU_IN_FULLCHIP_RESET) @ rs_client.c:844                                                                            
  [  212.995289] NVRM: nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status == NV_ERR_GPU_IN_FULLCHIP_RESET)  
  @ rs_server.c:259                                                                                                          
  [  212.995295] NVRM: GPU0 _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 10 sequence 3581!          
  [  212.995296] NVRM: GPU0 rpcRmApiFree_GSP: GspRmFree failed: hClient=0xc1d00071; hObject=0x5c000027;                      
  paramsStatus=0x00000000; status=0x0000000f                                                                                 
  [  212.995338] NVRM: GPU0 _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 10 sequence 3582!          
  [  212.995339] NVRM: GPU0 rpcRmApiFree_GSP: GspRmFree failed: hClient=0xc1d00071; hObject=0x5c00002b;                      
  paramsStatus=0x00000000; status=0x0000000f                                                                                 
  [  212.995339] NVRM: GPU0 nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status ==                           
  NV_ERR_GPU_IN_FULLCHIP_RESET) @ rs_client.c:844                                                                            
  [  212.995341] NVRM: nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status == NV_ERR_GPU_IN_FULLCHIP_RESET)  
  @ rs_server.c:259                                                                                                          
  [  212.995345] NVRM: GPU0 _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 10 sequence 3583!          
  [  212.995346] NVRM: GPU0 rpcRmApiFree_GSP: GspRmFree failed: hClient=0xc1d00071; hObject=0x5c00002c;                      
  paramsStatus=0x00000000; status=0x0000000f                                                                                 
  [  212.995346] NVRM: GPU0 nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status ==                           
  NV_ERR_GPU_IN_FULLCHIP_RESET) @ rs_client.c:844                                                                            
  [  212.995348] NVRM: nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status == NV_ERR_GPU_IN_FULLCHIP_RESET)  
  @ rs_server.c:259                                                                                                          
  [  212.995355] NVRM: GPU0 _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 10 sequence 3584!          
  [  212.995356] NVRM: GPU0 rpcRmApiFree_GSP: GspRmFree failed: hClient=0xc1d00071; hObject=0x5c00002a;                      
  paramsStatus=0x00000000; status=0x0000000f                                                                                 
  [  212.995411] NVRM: GPU0 _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 10 sequence 3585!          
  [  212.995412] NVRM: GPU0 rpcRmApiFree_GSP: GspRmFree failed: hClient=0xc1d00071; hObject=0x5c00002f;                      
  paramsStatus=0x00000000; status=0x0000000f                                                                                 
  [  212.995413] NVRM: GPU0 nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status ==                           
  NV_ERR_GPU_IN_FULLCHIP_RESET) @ rs_client.c:844                                                                            
  [  212.995415] NVRM: nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status == NV_ERR_GPU_IN_FULLCHIP_RESET)  
  @ rs_server.c:259                                                                                                          
  [  212.995423] NVRM: GPU0 _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 10 sequence 3586!          
  [  212.995424] NVRM: GPU0 rpcRmApiFree_GSP: GspRmFree failed: hClient=0xc1d00071; hObject=0x5c00002e;                      
  paramsStatus=0x00000000; status=0x0000000f                                                                                 
  [  212.995475] NVRM: GPU0 _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 10 sequence 3587!          
  [  212.995476] NVRM: GPU0 rpcRmApiFree_GSP: GspRmFree failed: hClient=0xc1d00071; hObject=0x5c000032;                      
  paramsStatus=0x00000000; status=0x0000000f                                                                                 
  [  212.995478] NVRM: GPU0 nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status ==                           
  NV_ERR_GPU_IN_FULLCHIP_RESET) @ rs_client.c:844                                                                            
  [  212.995481] NVRM: nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status == NV_ERR_GPU_IN_FULLCHIP_RESET)  
  @ rs_server.c:259                                                                                                          
  [  212.995486] NVRM: GPU0 _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 10 sequence 3588!          
  [  212.995487] NVRM: GPU0 rpcRmApiFree_GSP: GspRmFree failed: hClient=0xc1d00071; hObject=0x5c000033;                      
  paramsStatus=0x00000000; status=0x0000000f                                                                                 
  [  212.995487] NVRM: GPU0 nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status ==                           
  NV_ERR_GPU_IN_FULLCHIP_RESET) @ rs_client.c:844                                                                            
  [  212.995489] NVRM: nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status == NV_ERR_GPU_IN_FULLCHIP_RESET)  
  @ rs_server.c:259                                                                                                          
  [  212.995496] NVRM: GPU0 _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 10 sequence 3589!          
  [  212.995496] NVRM: GPU0 rpcRmApiFree_GSP: GspRmFree failed: hClient=0xc1d00071; hObject=0x5c000031;                      
  paramsStatus=0x00000000; status=0x0000000f                                                                                 
  [  212.995526] NVRM: GPU0 _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 10 sequence 3590!          
  [  212.995526] NVRM: GPU0 rpcRmApiFree_GSP: GspRmFree failed: hClient=0xc1d00071; hObject=0x5c000036;                      
  paramsStatus=0x00000000; status=0x0000000f                                                                                 
  [  212.995527] NVRM: GPU0 nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status ==                           
  NV_ERR_GPU_IN_FULLCHIP_RESET) @ rs_client.c:844                                                                            
  [  212.995529] NVRM: nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status == NV_ERR_GPU_IN_FULLCHIP_RESET)  
  @ rs_server.c:259                                                                                                          
  [  212.995536] NVRM: GPU0 _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 10 sequence 3591!          
  [  212.995537] NVRM: GPU0 rpcRmApiFree_GSP: GspRmFree failed: hClient=0xc1d00071; hObject=0x5c000035;                      
  paramsStatus=0x00000000; status=0x0000000f                                                                                 
  [  212.995612] NVRM: GPU0 _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 10 sequence 3592!          
  [  212.995616] NVRM: GPU0 rpcRmApiFree_GSP: GspRmFree failed: hClient=0xc1d0006f; hObject=0xa55a00e0;                      
  paramsStatus=0x00000000; status=0x0000000f                                                                                 
  [  212.995617] NVRM: GPU0 nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status ==                           
  NV_ERR_GPU_IN_FULLCHIP_RESET) @ rs_client.c:844                                                                            
  [  212.995623] NVRM: nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status == NV_ERR_GPU_IN_FULLCHIP_RESET)  
  @ rs_server.c:259                                                                                                          
  [  212.995644] NVRM: GPU0 _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 10 sequence 3593!          
  [  212.995645] NVRM: GPU0 rpcRmApiFree_GSP: GspRmFree failed: hClient=0xc1d0006f; hObject=0xa55a00c0;                      
  paramsStatus=0x00000000; status=0x0000000f                                                                                 
  [  212.995647] NVRM: GPU0 nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status ==                           
  NV_ERR_GPU_IN_FULLCHIP_RESET) @ rs_client.c:844                                                                            
  [  212.995653] NVRM: nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status == NV_ERR_GPU_IN_FULLCHIP_RESET)  
  @ rs_server.c:259                                                                                                          
  [  212.995671] NVRM: GPU0 _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 10 sequence 3594!          
  [  212.995673] NVRM: GPU0 rpcRmApiFree_GSP: GspRmFree failed: hClient=0xc1d0006f; hObject=0xa55a0040;                      
  paramsStatus=0x00000000; status=0x0000000f                                                                                 
  [  212.995674] NVRM: GPU0 nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status ==                           
  NV_ERR_GPU_IN_FULLCHIP_RESET) @ rs_client.c:844                                                                            
  [  212.995677] NVRM: nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status == NV_ERR_GPU_IN_FULLCHIP_RESET)  
  @ rs_server.c:259                                                                                                          
  [  212.995678] NVRM: nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status == NV_ERR_GPU_IN_FULLCHIP_RESET)  
  @ rs_server.c:1375                                                                                                         
  [  212.995684] NVRM: GPU0 _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 10 sequence 3595!          
  [  212.995685] NVRM: GPU0 rpcRmApiFree_GSP: GspRmFree failed: hClient=0xc1d0006f; hObject=0xa55a00b0;                      
  paramsStatus=0x00000000; status=0x0000000f                                                                                 
  [  212.995694] NVRM: GPU0 _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 10 sequence 3596!          
  [  212.995695] NVRM: GPU0 rpcRmApiFree_GSP: GspRmFree failed: hClient=0xc1d0006f; hObject=0xa55a00a0;                      
  paramsStatus=0x00000000; status=0x0000000f                                                                                 
  [  212.995699] NVRM: GPU0 _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 10 sequence 3597!          
  [  212.995701] NVRM: GPU0 rpcRmApiFree_GSP: GspRmFree failed: hClient=0xc1d0006f; hObject=0xa55a0090;                      
  paramsStatus=0x00000000; status=0x0000000f                                                                                 
  [  212.995706] NVRM: GPU0 _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 10 sequence 3598!          
  [  212.995707] NVRM: GPU0 rpcRmApiFree_GSP: GspRmFree failed: hClient=0xc1d0006f; hObject=0xa55a0080;                      
  paramsStatus=0x00000000; status=0x0000000f                                                                                 
  [  212.995711] NVRM: GPU0 _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 10 sequence 3599!          
  [  212.995712] NVRM: GPU0 rpcRmApiFree_GSP: GspRmFree failed: hClient=0xc1d0006f; hObject=0xa55a0070;                      
  paramsStatus=0x00000000; status=0x0000000f                                                                                 
  [  212.995717] NVRM: GPU0 _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 10 sequence 3600!          
  [  212.995718] NVRM: GPU0 rpcRmApiFree_GSP: GspRmFree failed: hClient=0xc1d0006f; hObject=0xa55a0060;                      
  paramsStatus=0x00000000; status=0x0000000f                                                                                 
  [  212.995724] NVRM: GPU0 _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 10 sequence 3601!          
  [  212.995725] NVRM: GPU0 rpcRmApiFree_GSP: GspRmFree failed: hClient=0xc1d0006f; hObject=0xa55a0050;                      
  paramsStatus=0x00000000; status=0x0000000f                                                                                 
  [  212.995873] NVRM: GPU0 _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 76 sequence 3602!          
  [  212.995875] NVRM: GPU0 nvCheckFailedNoLog: Check failed: (status == NV_OK) || (status == NV_ERR_GPU_IN_FULLCHIP_RESET)  
  @ gpu_user_shared_data.c:462                                                                                               
  [  212.995878] NVRM: GPU0 nvCheckOkFailedNoLog: Check failed: GPU lost from the bus [NV_ERR_GPU_IS_LOST] (0x0000000F)      
  returned from _gpushareddataSendDataPollRpc(pGpu, polledDataMask, pollingIntervalMs) @ gpu_user_shared_data.c:577          
  [  212.995880] NVRM: GPU0 nvCheckFailedNoLog: Check failed: _handlePollMaskHelper(pGpu, NV_FALSE, NV_TRUE) == NV_OK @      
  gpu_user_shared_data.c:152                                                                                                 
  [  212.995888] NVRM: GPU0 _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 10 sequence 3603!          
  [  212.995890] NVRM: GPU0 rpcRmApiFree_GSP: GspRmFree failed: hClient=0xc1d0006f; hObject=0xa55a0030;                      
  paramsStatus=0x00000000; status=0x0000000f                                                                                 
  [  212.995939] NVRM: GPU0 _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 10 sequence 3604!          
  [  212.995941] NVRM: GPU0 rpcRmApiFree_GSP: GspRmFree failed: hClient=0xc1d0006f; hObject=0xa55a0020;                      
  paramsStatus=0x00000000; status=0x0000000f                                                                                 
  [  212.996483] NVRM: GPU0 _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 10 sequence 3605!          
  [  212.996484] NVRM: GPU0 rpcRmApiFree_GSP: GspRmFree failed: hClient=0xc1d00071; hObject=0x5c000014;                      
  paramsStatus=0x00000000; status=0x0000000f                                                                                 
  [  212.996485] NVRM: GPU0 nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status ==                           
  NV_ERR_GPU_IN_FULLCHIP_RESET) @ rs_client.c:844                                                                            
  [  212.996492] NVRM: nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status == NV_ERR_GPU_IN_FULLCHIP_RESET)  
  @ rs_server.c:259                                                                                                          
  [  212.996523] NVRM: GPU0 _issueRpcAndWait: rpcSendMessage failed with status 0x0000000f for fn 10 sequence 3606!          
  [  212.996524] NVRM: GPU0 rpcRmApiFree_GSP: GspRmFree failed: hClient=0xc1d00071; hObject=0x5c000013;                      
  paramsStatus=0x00000000; status=0x0000000f                                                                                 
  [  212.996525] NVRM: GPU0 nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status ==                           
  NV_ERR_GPU_IN_FULLCHIP_RESET) @ rs_client.c:844                                                                            
  [  212.996624] NVRM: nvAssertFailedNoLog: Assertion failed: (status == NV_OK) || (status == NV_ERR_GPU_IN_FULLCHIP_RESET)  
  @ rs_server.c:259                                                                                                          
  [  237.995380] r8152 2-3.4.2:1.0 enp0s13f0u3u4u2: NETDEV WATCHDOG: CPU: 19: transmit queue 0 timed out 5005 ms             
  [  237.995395] r8152 2-3.4.2:1.0 enp0s13f0u3u4u2: Tx timeout                                                               
  [  243.003685] r8152 2-3.4.2:1.0 enp0s13f0u3u4u2: NETDEV WATCHDOG: CPU: 19: transmit queue 0 timed out 5008 ms             
  [  243.003711] r8152 2-3.4.2:1.0 enp0s13f0u3u4u2: Tx timeout                                                               
  [  243.291481] xhci_hcd 0000:00:0d.0: xHCI host not responding to stop endpoint command                                    
  [  243.291489] xhci_hcd 0000:00:0d.0: xHCI host controller not responding, assume dead                                     
  [  243.291512] xhci_hcd 0000:00:0d.0: HC died; cleaning up                                                                 
  [  243.291537] usb 2-2: USB disconnect, device number 11                                                                   
  [  243.291539] usb 2-2.4: USB disconnect, device number 12                                                                 
  [  243.291541] r8152-cfgselector 2-2.4.4: USB disconnect, device number 13                                                 
  [  243.291614] r8152 2-3.4.2:1.0 enp0s13f0u3u4u2: Tx status -108                                                           
  [  243.291617] r8152 2-3.4.2:1.0 enp0s13f0u3u4u2: Tx status -108                                                           
  [  243.291618] r8152 2-3.4.2:1.0 enp0s13f0u3u4u2: Tx status -108                                                           
  [  243.291620] r8152 2-3.4.2:1.0 enp0s13f0u3u4u2: Tx status -108                                                           
  [  243.291642] r8152 2-3.4.2:1.0 enp0s13f0u3u4u2: Get ether addr fail                                                      
  [  243.337156] usb 2-3: USB disconnect, device number 14                                                                   
  [  243.337161] usb 2-3.4: USB disconnect, device number 15                                                                 
  [  243.337164] usb 2-3.4.1: USB disconnect, device number 16                                                               
  [  243.337166] usb 2-3.4.1.3: USB disconnect, device number 18                                                             
  [  243.373806] r8152-cfgselector 2-3.4.2: USB disconnect, device number 17                                                 
  [  243.408605] usb 2-3.4.3: USB disconnect, device number 19      
```

</details>

**Comment by adrianhoehne** [comment]
@azmeuk You brought me into a good direction so I could solve my Xid 79 issue with an eGPU setup and my RTX 2060.  I was then also able to reproduce it. As long as there is no CUDA access, the connection stays stable. After I load nvidia_uvm, and call nvidia-smi, the card falls off the bus.  I guess the problem is between the nvidia_uvm module and ASPM. 

However, pcie_aspm=off doesn't mean really off. I also relied on it. But it also depends on what policy is used on your system and your BIOS settings. In my system it was still enabled for this pcie branch; I saw it by trying to reproduce what you explained.
`sudo lspci -vv -s 3d:00.0 | grep -iE 'LnkCtl'`

I've got:
`LnkCtl:	ASPM L1 Enabled; RCB 64 bytes, Disabled- CommClk+`

I got my setup stable by disabling ASPM via setpci.  
`sudo setpci -s 3d:00.0 CAP_EXP+10.w` gave me 0142
Which means ASPM L1 enabled, CommClk enabled and ClockPM enabled. 

So, I changed it to 0140 with the command:
`sudo setpci -s 3d:00.0 CAP_EXP+10.w`

Remember, your card is on 2d not 3d. 

I guess the driver has some problems with ASPM.

System Details:
NVIDIA-SMI 580.126.09             Driver Version: 580.126.09     CUDA Version: 13.0 

System:
  Kernel: 6.8.0-94-generic x86_64 bits: 64 compiler: N/A Console: pty pts/0
    Distro: Ubuntu 22.04.5 LTS (Jammy Jellyfish)
Machine:
  Type: Laptop System: Dell product: Precision 7520 v: N/A serial: <superuser required>
  Mobo: Dell model: 0NP5CM v: A00 serial: <superuser required> UEFI: Dell v: 1.26.0
Graphics:
  Device-1: Intel HD Graphics 530 vendor: Dell driver: i915 v: kernel bus-ID: 00:02.0
  Device-2: NVIDIA GM107GLM [Quadro M1200 Mobile] vendor: Dell driver: nvidia v: 580.126.09
    bus-ID: 01:00.0
  Device-3: NVIDIA TU106 [GeForce RTX 2060 12GB] vendor: ASUSTeK driver: nvidia v: 580.126.09
    bus-ID: 3d:00.0

**Comment by Cyrille37** [comment]
Hi & thanks for reports :-)

I did many tries with grub flags & modprob configs but cannot have my RTS 5060 Ti to be stable for long runs.

I looked for @adrianhoehne tip, but the ASPM seems to already off (_but I'm not expert_) :

```
$  lspci -k -d ::03xx
00:02.0 VGA compatible controller: Intel Corporation Raptor Lake-P [Iris Xe Graphics] (rev 04)
	Subsystem: CLEVO/KAPOK Computer Raptor Lake-P [Iris Xe Graphics]
	Kernel driver in use: i915
	Kernel modules: i915, xe
05:00.0 VGA compatible controller: NVIDIA Corporation Device 2d04 (rev a1)
	Subsystem: PNY Device 1440
	Kernel driver in use: nvidia
	Kernel modules: nvidiafb, nouveau, nvidia_drm, nvidia

$ sudo lspci -vv -s 05:00.0 | grep -iE 'LnkCtl'
		LnkCtl:	ASPM Disabled; RCB 64 bytes, Disabled- CommClk+
		LnkCtl2: Target Link Speed: 32GT/s, EnterCompliance- SpeedDis-
		LnkCtl3: LnkEquIntrruptEn- PerformEqu-
```

Is it a possible solution around the `LnkCtl2: Target Link Speed: 32GT/s, EnterCompliance- SpeedDis-` like reducing the speed ?

**Comment by adrianhoehne** [comment]
@Cyrille37 Yes, at least for me it was possible. But you need to google the right hex value for it or ask your LLM. The register is visible with: 
sudo setpci -s 00:1d.0 CAP_EXP+30.w

My value is 0003 which is 8GT/s. I tried, and it worked to reduce the speed, but at the time it didn't solve my problem. However, I forgot to mention that I didn't use the open driver, so it may behave differently.

**Comment by Cyrille37** [comment]
Hello
Same for me, I downgraded the speed too, but after undred of inferences with Yolo, the bus as fallen 😩

**Comment by bom-singiali** [comment]
Hello,

[nvidia-bug-report.log_crashed.gz](https://github.com/user-attachments/files/26389628/nvidia-bug-report.log_crashed.gz)
[nvidia-bug-report.log_safe_mode.gz](https://github.com/user-attachments/files/26389629/nvidia-bug-report.log_safe_mode.gz)
[nvidia-bug-report.log.gz](https://github.com/user-attachments/files/26389630/nvidia-bug-report.log.gz)

## Additional data point — different hardware, same Xid 79

**Setup:** Minisforum MS-02 Ultra 9 (285 HX) + Gigabyte AORUS RTX 5060Ti AI BOX via Intel JHL9580 TB5 (USB4 v2 80Gbps). CachyOS, kernel 6.19.10, nvidia-open 595.58.03.

**Symptoms:** Identical Xid 79 on every boot at ~t=6.2s. GPU detected, then immediately falls off the bus.

**Root cause found:** The Linux Thunderbolt driver's `host_reset=true` (default) resets the host router at ~6.2s, tearing down the PCIe tunnel right after NVIDIA driver init.

**Workaround:**
```
# /etc/modprobe.d/thunderbolt.conf
options thunderbolt host_reset=false
```

GPU boots stable with this — no Xid 79, nvidia-smi works, PRIME offload and gaming functional.

**Additional finding:** PCIe tunnel stuck at Gen1 (2.5 GT/s) despite 80 Gbps TB5 link. JHL9580 downstream ports advertise `LnkCap2: 2.5GT/s ONLY`. Measured H2D bandwidth: ~0.69 GB/s vs expected ~6-7 GB/s.

**Windows 11 on same hardware:** eGPU works for gaming but system hard-freezes after exiting a game — suggests this is cross-platform, not Linux-specific.

nvidia-bug-report attached.

Many Thanks
Bom Singiali

**Comment by pwoznet** [comment]
Hello,

For anyone struggling with RTX 5060Ti + WKG-L1970C TB3/4 dock, it seems that (at least with my setup) limiting the PCIe to Gen2 makes the CUDA computation workloads pretty stable. By "stable" I mean no xid79 events. 

My laptop HP840 G10 doesn't support limiting PCIe speeds in the BIOS, so the only solution is to force it via setpci command:

Steps:

1. Use lcpci command to find your GPU location. Some say one should use the bridge id - I used the GPU, works fine.

lspci |grep "RTX 5060"
05:00.0 VGA compatible controller: NVIDIA Corporation GB206 [GeForce RTX 5060 Ti] (rev a1)

2. Get the script and save it locally (/root/speedpci.sh)

https://alexforencich.com/wiki/en/pcie/set-speed

3. Key step, from my experience, the capping to Gen2 must be done before loading the nvidia module, otherwise the driver will try to act clever and bump up the pcie speed back to Gen3 (with my dock/laptop combo). It can be done by using "install" option in the nvidia.conf in /etc/modprobe.d file.

For example: 

```
/etc/modprobe.d# more nvidia.conf 
# Blacklist display modules for compute-only
blacklist nvidia_drm
blacklist nvidia_modeset

# Override system softdep - only load nvidia-uvm, skip drm/modeset (compute-only)
softdep nvidia post: nvidia-uvm

# Disable Resizable BAR (resize fails with small bridge windows)
options nvidia NVreg_EnableResizableBar=0

# Disable dynamic power management (prevents D3cold issues over Thunderbolt)
options nvidia NVreg_DynamicPowerManagement=0

# Force eGPU mode (bypasses Thunderbolt bridge detection for TB4/TB5 enclosures)
options nvidia NVreg_ForceExternalGpu=1

options nvidia Vreg_EnablePCIeGen3=3

options nvidia NVreg_EnableGpuFirmware=0

# Lock clocks after driver loads (prevents ASPM-triggered link degradation)
install nvidia /usr/local/bin/nvidia-egpu-setup.sh $CMDLINE_OPTS

```
Next, create the /usr/local/bin/nvidia-egpu-setup.sh script, replace the "/root/speedpci.sh 05:00.0 2" with your system-specifc value (most likely you can skip the gpu clocks locking etc.):

```
more /usr/local/bin/nvidia-egpu-setup.sh
#!/bin/bash
# Clock locking wrapper for nvidia module load


logger -t nvidia-egpu "set pcie gen2..."
/root/speedpci.sh 05:00.0 2

logger -t nvidia-egpu "Install directive triggered with opts: ${@}"

# Load the actual nvidia module first
/sbin/modprobe --ignore-install nvidia "$@"
ret=$?

if [ $ret -ne 0 ]; then
    logger -t nvidia-egpu "modprobe failed with $ret"
    exit $ret
fi

logger -t nvidia-egpu "Module loaded, waiting for nvidia-smi..."

# Wait for nvidia-smi to respond
for i in {1..60}; do
    if nvidia-smi --query-gpu=name --format=csv,noheader &>/dev/null; then
        logger -t nvidia-egpu "nvidia-smi responding after ${i}s"
        break
    fi
    sleep 1
done

if ! nvidia-smi --query-gpu=name --format=csv,noheader &>/dev/null; then
    logger -t nvidia-egpu "Timeout - nvidia-smi not responding"
    exit 0  # Don't fail module load
fi

sleep 2

logger -t nvidia-egpu "Locking clocks..."
nvidia-smi -pm 1
nvidia-smi -lgc 3090,3090 
#nvidia-smi -lmc 15001,15001
nvidia-smi -pl 180 
logger -t nvidia-egpu "Complete"

```

4. Reboot and check the link parameters via nvidia-smi -q, look for pci section, you should see:

 GPU Link Info
            PCIe Generation
                Max                                    : 2
                Current                                : 2
                Device Current                         : 2
                Device Max                             : 5
                Host Max                               : 1
            Link Width
                Max                                    : 8x
                Current                                : 4x

Both Max and Current should be "2", if Max is "3" as soon as any cuda load starts, the driver re-trains the link back to Gen3.

To summarise, before I've tried all the tricks mentioned here and there related to pcie power management, locking clocks but nothing really helped. With PCIe speed locked to 5GT (gen2), long AI/ML cuda sessions seem feasible. Of course, running a Gen5 GPU in Gen2 mode isn't perfect, but surely better than "falling of the bus" every 5-15 min.


Config info:

HP EliteBook 840 G10 (Intel)
WKG--L19c70 egpu dock tb3/4, "reagle" 50cm TB4 cable.
Intel Corporation JHL7540 Thunderbolt 3 Bridge [Titan Ridge DD 2018] (rev 06)
MSI Ventus 2x, 5060Ti

Linux pwozg10l 6.17.0-22-generic #22~24.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Mar 26 15:25:54 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

GRUB_CMDLINE_LINUX_DEFAULT="pcie_aspm=force pcie_aspm.policy=performance thunderbolt.host_reset=false intel_iommu=off iommu=pt pci=assign-busses hpbussiz
e=0x33 hpmmiosize=256M hpmmioprefsize=16G realloc pcie_port_pm=off thunderbolt.clx=0"
Intel Corporation JHL7540 Thunderbolt 3 Bridge [Titan Ridge DD 2018] (rev 06)

Driver Version                                         : 595.58.03
CUDA Version                                           : 13.2


Regards,
Pawel W.

**Comment by Cyrille37** [comment]
Hi @pwoznet . Thank you for this new proposition, I'll try today :-)

Before trying your solution, I can tell that upgrading `nvidia-driver` from 590 to 595 is important : I've just done and can chat with `llama.cpp` and successfully doing some code refactoring with `opencode` using `gpt-oss-20b-UD-Q4_K_XL.gguf`. The "Xid 79 GPU has fallen off the bus" only came when make ~3000 loops for image detection with `Yolo26`.

Let's give your solution a go! I'll come back soon :-)
